<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Action names (to do)
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 58
 *  Location : locale/en-utf8/actions.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1362'] = 'My settings';
$lang['1305'] = 'Clear the history of changes';
$lang['1295'] = 'Rollback';
$lang['1284'] = 'View keywords';
$lang['1283'] = 'View term';
$lang['1005'] = 'Merge dictionaries';
$lang['24_hours'] = '24 Hours';
$lang['1105'] = 'Send an e-mail';
$lang['1095'] = 'Suggest a term';
$lang['1093'] = 'Unsubscribe';
$lang['1087'] = 'Subscribe';
$lang['1072'] = 'Move to';
$lang['1036'] = 'Send';
$lang['1035'] = 'Preview';
$lang['1007'] = 'Get HTML-code for search form';
$lang['1006'] = 'Clean search query cache';
$lang['1023'] = 'Are you sure to clean cache?';
$lang['1004'] = 'Cache usage';
$lang['1003'] = 'Recount the number of terms for each dictionary';
$lang['1002'] = 'Check for unused keywords';
$lang['1001'] = 'Send a message to Glossword Support Team';
$lang['3_maintenance'] = 'Maintenance';
$lang['page_refresh'] = 'Refresh the page';
$lang['2_continue'] = 'Continue';
$lang['3_property'] = 'Properties';
$lang['3_change'] = 'Change';
$lang['3_logout'] = 'Logout';
$lang['3_send'] = 'Send';
$lang['3_add_term'] = 'Add a term';
$lang['3_next'] = 'Next';
$lang['3_register'] = 'New account';
$lang['3_import'] = 'Import';
$lang['3_clean'] = 'Clean';
$lang['3_add_dict'] = 'New dictionary';
$lang['3_browse'] = 'Browse';
$lang['3_cancel'] = 'Cancel';
$lang['3_save'] = 'Save';
$lang['1_prevd'] = 'Prev %d';
$lang['1_nextd'] = 'Next %d';
$lang['1_prevpage'] = 'Prev';
$lang['3_reset'] = 'Reset';
$lang['3_down'] = 'Down';
$lang['3_up'] = 'Up';
$lang['3_more'] = 'More&#8230;';
$lang['3_export'] = 'Export';
$lang['3_create'] = 'Create';
$lang['3_edit'] = 'Edit';
$lang['3_remove_term'] = 'Remove this term';
$lang['3_remove_defn'] = 'Remove this definition';
$lang['3_remove_trns'] = 'Remove this translation';
$lang['3_remove_abbr'] = 'Remove this abbreviation';
$lang['3_remove'] = 'Remove';
$lang['3_add_defn'] = 'Add a definition';
$lang['3_add_trns'] = 'Add a translation';
$lang['3_add_abbr'] = 'Add an abbreviation';
$lang['3_add'] = 'Add';
$lang['3_cfg'] = 'Configuration';
$lang['3_update'] = 'Update';
/**
 * The end of translation file.
 */
?>