<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Topics
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 5
 *  Location : locale/en-utf8/addon_topics.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['2_page_topic_browse'] = 'The list of topics';
$lang['3_undertopic'] = 'Parent topic';
$lang['3_add_subtopic'] = 'Add subtopic';
$lang['3_remove_topic'] = 'Remove this topic';
$lang['3_add_topic'] = 'New topic';
/**
 * The end of translation file.
 */
?>