<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom alphabetic order
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/en-utf8/addon_custom-az.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1293'] = 'The default sorting order';
$lang['1292'] = 'Letter';
$lang['1291'] = 'Activate the profile';
/**
 * The end of translation file.
 */
?>