<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Abbreviation
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/en-utf8/addon_abbr.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['id_dict_help'] = 'Dictionary, which the abbreviation will be used.';
$lang['id_abbr_help'] = 'Abbreviation ID, use [0-9] only. Cannot be changed later. Used in <tt>&lt;(abbr|trns) lang=&quot;{Abbreviation ID}&quot;&gt;</tt>.';
$lang['id_abbr'] = 'Abbreviation ID';
$lang['science'] = 'Science';
$lang['languages'] = 'Language names';
$lang['linguistics'] = 'Linguistics';
$lang['speech'] = 'Parts of speech';
$lang['custom'] = 'Custom';
$lang['id_group'] = 'Group';
$lang['abbr_long'] = 'Long form';
$lang['abbr_short'] = 'Short form';
/**
 * The end of translation file.
 */
?>