<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Error message
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 39
 *  Location : locale/en-utf8/err.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1370'] = 'Incorrect fields found.';
$lang['1348'] = 'No items selected';
$lang['1347'] = 'Time to idle, minutes: %s';
$lang['1346'] = 'Minutes passed: %s';
$lang['1345'] = 'Authorization required. Session expired or does not exist.';
$lang['1344'] = 'You have logged out.';
$lang['1343'] = 'Authorization required. Session does not exist.';
$lang['1342'] = 'Session expired in case of inactivity.';
$lang['1297'] = 'No records found.';
$lang['1255'] = 'No data';
$lang['1254'] = 'Too many records. The maximum number: %s. You have inserted: %s.';
$lang['1090'] = 'Incorrect e-mail address. Try again.';
$lang['1079'] = 'Errors';
$lang['reason_26'] = 'Term does not exist.';
$lang['reason_25'] = 'Term already exists';
$lang['reason_24'] = 'Your account has been activated. Login and password were send to e-mail, chosen on registration page.';
$lang['reason_23'] = 'Wrong activation key.';
$lang['reason_22'] = 'A new password has been created. Activation key has been sent to the e-mail address on record for your account.';
$lang['reason_21'] = 'Sorry, but your account is currently inactive. Please contact the site administrator for more information.';
$lang['reason_20'] = 'You have specified an incorrect username or an invalid password.';
$lang['reason_19'] = 'Specified password is too long.';
$lang['reason_18'] = 'That e-mail address cannot be used as it already exists.';
$lang['reason_17'] = 'Can\'t send mail to %s.';
$lang['reason_16'] = 'Current account disabled or awaiting for activation.';
$lang['reason_15'] = 'Selected login already exists. Try another one.';
$lang['reason_14'] = 'The new passwords doesn\'t match. Try again.';
$lang['reason_13'] = 'Permission denied';
$lang['reason_12'] = 'No such topic';
$lang['reason_11'] = 'Can\'t remove';
$lang['reason_10'] = 'File `%s` not found.';
$lang['reason_9'] = 'Incorrect';
$lang['reason_8'] = 'Function %s not installed.';
$lang['reason_6'] = 'Unable to load `iconv\' or `recode\' PHP-extension.';
$lang['reason_5'] = 'No matches.';
$lang['reason_4'] = 'No dictionaries found.';
$lang['reason_3'] = 'Dictionaries found in this topic.';
$lang['reason_2'] = 'There are more topics inside this topic.';
$lang['reason_1'] = 'Last topic. At least one topic should exist.';
$lang['reason_7'] = 'No dictionaries found.';
/**
 * The end of translation file.
 */
?>