<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : HTML Editor
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 19
 *  Location : locale/en-utf8/html_editor.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['ed_tagopen'] = 'tag open';
$lang['ed_tagclose'] = 'tag close';
$lang['ed_dots'] = 'dots';
$lang['ed_degree'] = 'degrees';
$lang['ed_registered'] = 'registered mark';
$lang['ed_copyright'] = 'copyright mark';
$lang['ed_eurosign'] = 'euro sign';
$lang['ed_trademark'] = 'trademark';
$lang['ed_underline'] = 'underline';
$lang['prompt_url'] = 'Enter URL (Example: http://glossword.info/)';
$lang['prompt_lnk'] = 'Enter a link (term for search)';
$lang['prompt_txt'] = 'Enter text (this text will be linked)';
$lang['ed_nbsp'] = 'non-breakable space';
$lang['ed_quot'] = 'quotes';
$lang['ed_lapki'] = 'quotes';
$lang['ed_elochki'] = 'quotes';
$lang['ed_p'] = 'paragraph';
$lang['ed_em'] = 'italic';
$lang['ed_bold'] = 'bold';
/**
 * The end of translation file.
 */
?>