<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Mail messages
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/en-utf8/mail.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1350'] = 'An automatic notification from site %s';
$lang['mail_newuser_subj'] = 'Welcome to site {SITENAME}';
$lang['mail_newpass_subj'] = 'New password activation';
$lang['mail_newuser'] = '<p>Hello {USERNAME}.</p>
<p>Please keep this email for your records. Your account information:</p>
<p>{LOGIN}: <b>{U_LOGIN}</b> <br />{PASSWORD}: <b>{U_PASSWORD}</b></p>
<p>Use the following URL to log in: <br/>{LOGIN_URL}</p>
<p>If you have any questions, contact to {CONTACT_EMAIL}.</p>';
$lang['mail_newpass'] = '<p>Hello {USERNAME}</p> <p>You have requested a new password be sent for your account on {SITENAME}.</p> <p>To use the new password click the link provided below: <br/> {U_ACTIVATE}</p>';
$lang['2_page_user_register'] = 'New user registration';
/**
 * The end of translation file.
 */
?>