<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Option text
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 201
 *  Location : locale/en-utf8/options.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1401'] = 'Display by default';
$lang['1374'] = 'Save in the history of changes';
$lang['1369'] = 'The task execution time';
$lang['1364'] = 'Dictionary ID';
$lang['1361'] = 'Allow simultaneous access';
$lang['1360'] = 'Publish imported terms';
$lang['1359'] = 'Merge identical terms';
$lang['1356'] = 'UTC Coordinated Universal Time';
$lang['1355'] = 'Allowed editing own profile';
$lang['1354'] = 'Receive system events';
$lang['1352'] = 'Prefix for subject';
$lang['1330'] = 'Add component';
$lang['1329'] = 'Add menu item';
$lang['1328'] = 'Icon';
$lang['1327'] = 'Create a new';
$lang['1326'] = 'Hidden';
$lang['1325'] = 'Secondary menu';
$lang['1324'] = 'Primary menu';
$lang['1323'] = 'Placement';
$lang['1322'] = 'Translation string';
$lang['1321'] = 'File name';
$lang['1320'] = 'Published';
$lang['1319'] = 'Menu manager';
$lang['1318'] = 'Allowed editing other users\' pages';
$lang['1317'] = 'Allowed creating and editing own pages';
$lang['1316'] = 'Allowed changing password';
$lang['1315'] = 'Allowed changing login';
$lang['1314'] = 'Allowed changing e-mail address';
$lang['1313'] = 'Allowed running maintenance tasks';
$lang['1312'] = 'Allowed editing other users\' topics';
$lang['1311'] = 'Don\'t type a diacritical marks if you don\'t want to include them on sorting.';
$lang['1310'] = 'Uppercase.';
$lang['1309'] = 'Sorting';
$lang['1308'] = 'Incomplete terms are marked by symbol ‘%s’';
$lang['1304'] = 'Enable SEF (Search engine friendly URLs)';
$lang['1303'] = 'Link creation mode';
$lang['1302'] = 'Text';
$lang['1301'] = 'Alphanumeric';
$lang['1300'] = 'Numeric only';
$lang['1299'] = 'Save as file';
$lang['1298'] = 'Removed terms';
$lang['1296'] = 'The number of days in the history of changes';
$lang['1294'] = 'History of changes';
$lang['1288'] = 'Show';
$lang['1287'] = 'As list';
$lang['1286'] = 'As table';
$lang['1280'] = 'All letters are case insensitive (A = a).';
$lang['1279'] = 'Refresh image';
$lang['1278'] = 'Friend\'s e-mail';
$lang['1275'] = 'Send the page';
$lang['1274'] = 'Sorting';
$lang['1273'] = 'By name';
$lang['1272'] = 'By date';
$lang['1271'] = 'Add to search';
$lang['1270'] = 'As in the system settings';
$lang['1268'] = 'Incomplete terms';
$lang['1267'] = 'Term is complete';
$lang['1265'] = 'Allowed editing program settings';
$lang['1264'] = 'Allowed exporting terms';
$lang['1263'] = 'Allowed importing terms';
$lang['1262'] = 'Allowed creating and editing users\' profiles';
$lang['1261'] = 'Allowed creating and editing own terms';
$lang['1260'] = 'Allowed editing other users\' dictionary settings';
$lang['1259'] = 'Allowed editing other users\' terms';
$lang['1258'] = 'Allowed creating and editing own dictionaries';
$lang['1257'] = 'Allowed creating and editing own topics';
$lang['1256'] = 'Enable links for terms in this field';
$lang['1197'] = 'Use the advantage of Content-Type for XHTML 1.1-compatible browsers';
$lang['1158'] = 'Merge new values with an existent values';
$lang['1154'] = 'Show topics descriptions in catalog';
$lang['1153'] = 'Include the date of creation and modification';
$lang['1152'] = 'Imported values will completely replace an existing values';
$lang['srch_topic'] = 'Search in topic';
$lang['srch_dict'] = 'Search in dictionary';
$lang['1150'] = 'terms/second';
$lang['1149'] = 'Average speed';
$lang['1140'] = 'Author';
$lang['1139'] = 'Check for an existent term';
$lang['1128'] = 'The number of days in the cache of search queries';
$lang['1127'] = 'Clear selected dictionaries after merging';
$lang['1126'] = 'To select multiple items use CTRL key and left mouse button.';
$lang['1125'] = 'Select one or more dictionaries to merge.';
$lang['1124'] = 'Selected dictionaries will be merged to';
$lang['1123'] = 'Read first line';
$lang['1122'] = 'Definitions terminated by';
$lang['1120'] = 'Fields enclosed by';
$lang['1119'] = 'Fields terminated by';
$lang['1118'] = 'Automatically parse hyperlinks';
$lang['1117'] = 'The image will be scaled down if it\'s too big in pixel size.';
$lang['1132'] = 'Maximum size';
$lang['1130'] = 'Maximum width, pixels';
$lang['1131'] = 'Maximum height, pixels';
$lang['is_abbr_long'] = 'Display long abbreviation form';
$lang['1129'] = 'The number of days in the log of search queries';
$lang['period'] = 'Period';
$lang['is_use_avatar'] = 'Use avatar';
$lang['1111'] = 'Your current avatar';
$lang['1110'] = 'The following file types are allowed';
$lang['srch_7'] = 'Unapproved terms';
$lang['is_show_date_modified'] = 'Show modification date';
$lang['is_show_authors'] = 'Show the list of editors';
$lang['1103'] = 'The time including current adjustment is';
$lang['1101'] = 'Enable logging search queries';
$lang['1100'] = 'Enable logging e-mail messages';
$lang['1099'] = 'Enable logging referring pages';
$lang['1098'] = 'The character used as separator in "breadcrumbs"';
$lang['1097'] = 'The character used as separator in &lt;title&gt;';
$lang['1096'] = 'The number of terms per page with search results';
$lang['1084'] = 'Select a dictionary';
$lang['1080'] = 'Subject';
$lang['1077'] = 'Subscribers';
$lang['1074'] = 'Add subpage';
$lang['1073'] = 'Uniform resource identifier (URI)';
$lang['1068'] = 'Path to exported files';
$lang['1066'] = 'Show dictionary short description in catalog';
$lang['1065'] = 'Show icons in catalog';
$lang['1064'] = 'Show the number of terms in dictionary for catalog';
$lang['1063'] = 'The number of dictionaries in the Top 10';
$lang['1062'] = 'The number of recently updated dictionaries';
$lang['1060'] = 'Icon file';
$lang['1059'] = 'Program code';
$lang['1058'] = 'Contents';
$lang['1055'] = 'Sensitive to letters [a-z and letters from national alphabet]';
$lang['1054'] = 'Sensitive to alphanumeric [a-z0-9]';
$lang['1053'] = 'Ideographic characters';
$lang['1052'] = 'Halfwidth and Fullwidth Forms';
$lang['1051'] = 'Diacritics';
$lang['1050'] = 'Basic Latin';
$lang['1049'] = 'Sensitive to diacritics [ā-ž]';
$lang['1048'] = 'Sensitive to numbers [0-9]';
$lang['1047'] = 'Filter stopwords';
$lang['1046'] = 'Filter special characters';
$lang['1045'] = 'Show definition contents as tooltip for term';
$lang['1044'] = 'The compatibility of versions';
$lang['1040'] = 'Convert escape sequences';
$lang['1039'] = 'Keep whitespace characters';
$lang['1038'] = 'Search is disabled';
$lang['1034'] = 'Documentation errors';
$lang['1033'] = 'Interface translation errors';
$lang['1032'] = 'Customizing issues';
$lang['1031'] = 'Suggestions and requests';
$lang['1030'] = 'Configuration issues';
$lang['1029'] = 'General issues';
$lang['1027'] = 'Operating system';
$lang['1026'] = 'PHP version';
$lang['1025'] = 'Product version';
$lang['is_dict_as_index'] = 'Assign this dictionary as main page';
$lang['is_show_full'] = 'Show the full text of definitions instead of preview';
$lang['after_post_3'] = 'Open the last search results';
$lang['after_post_is_save_term'] = 'Save HTML-form settings';
$lang['after_post_1'] = 'Update dictionary statistics';
$lang['after_post'] = 'After&#160;posting…';
$lang['xml_is_term_id'] = 'Term ID';
$lang['alphabetic_order'] = 'Alphabetic order';
$lang['fields_to_edit'] = 'Fields to edit';
$lang['min_srch_length'] = 'Minimum search string length';
$lang['user_notice'] = 'Send notice of registration';
$lang['allow_user'] = 'Access allowed';
$lang['allow_htmleditor'] = 'Use HTML-editor';
$lang['allow_leecher'] = 'Activate anti-leecher';
$lang['user_dictionaries'] = 'Assigned dictionaries';
$lang['date_logged'] = 'Last logged date';
$lang['date_register'] = 'Registered at';
$lang['allow_showcontact'] = 'Show contact information';
$lang['lang_source'] = 'Source language';
$lang['is_specialchars'] = 'Include special characters when checking for an existent term';
$lang['admin_url'] = 'Path to administration page';
$lang['login_url'] = 'Path to login page';
$lang['admin_host'] = 'Administrative host';
$lang['login_host'] = 'Login host';
$lang['admin_proto'] = 'Administrative protocol';
$lang['login_proto'] = 'Login protocol';
$lang['path_cache'] = 'Path to cached sql-queries';
$lang['path_log'] = 'Path to log-files';
$lang['site_desc'] = 'Site description';
$lang['site_name'] = 'Site name';
$lang['default_lang'] = 'Default language';
$lang['cache_lifetime'] = 'Cache expired in minutes (0 - never expired)';
$lang['cache_zlib'] = 'Use compression GZip to store/read cache files';
$lang['cache_is'] = 'Enable cache engine';
$lang['1133'] = 'The maximum number of characters for each definition in the list of terms';
$lang['time_upd'] = 'The number of days each dictionary is marked as updated';
$lang['time_new'] = 'The number of days each dictionary is marked as new';
$lang['page_limit'] = 'The number of terms per page';
$lang['sys'] = 'System';
$lang['enter_xml'] = 'Enter a valid XML-code';
$lang['date_modif'] = 'Last modified';
$lang['date_created'] = 'Created at';
$lang['dict_name'] = 'Title';
$lang['announce'] = 'Short description';
$lang['keywords'] = 'Keywords';
$lang['visual_theme'] = 'Visual theme';
$lang['srch_selectdict'] = 'Select dictionary';
$lang['validate'] = 'Validate';
$lang['overwrite'] = 'Overwrite an existent values with new values';
$lang['till_time'] = 'till';
$lang['from_time'] = 'from';
$lang['dictdump_list'] = 'From the list';
$lang['allow_letters'] = 'Show alphabetic toolbar (A-Z)';
$lang['sysname'] = 'Database table name';
$lang['options'] = 'Options';
$lang['ed_xref'] = 'place link to a term';
/**
 * The end of translation file.
 */
?>