<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Current status (present tense)
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 9
 *  Location : locale/en-utf8/status.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['2_page_custom_az_browse'] = 'Browsing profiles';
$lang['2_page_term_viewkeywords'] = 'Viewing a search keywords';
$lang['2_page_term_browse'] = 'The list of terms';
$lang['1107'] = 'Viewing profile';
$lang['2_page_32'] = 'Browsing current subscriptions';
$lang['2_page_sys_maintenance'] = 'System maintenance';
$lang['2_page_user_browse'] = 'The list of users';
$lang['2_page_17'] = 'Updating the term';
$lang['2_page__srch'] = 'Searching...';
/**
 * The end of translation file.
 */
?>