<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Common words to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://glossword.info/tkit/)
 *  © 2002-2004 Dmitry N. Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Common words
 *  Topic    : Stop words
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 146
 *  Location : locale/en-utf8/stop_words.php
 *  Created  : 25 Aug 2003, 00:25
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry <dev at glossword dot info>
 */
$lang['195'] = '\n';
$lang['146'] = 'ALL';
$lang['145'] = 'AM';
$lang['144'] = 'AND';
$lang['143'] = 'ARE';
$lang['142'] = 'ANY';
$lang['141'] = 'AS';
$lang['140'] = 'AT';
$lang['139'] = 'BE';
$lang['138'] = 'BUT';
$lang['137'] = 'BY';
$lang['136'] = 'CAN';
$lang['135'] = 'CANT';
$lang['134'] = 'DID';
$lang['133'] = 'DO';
$lang['132'] = 'DOES';
$lang['131'] = 'DOESNT';
$lang['130'] = 'DONT';
$lang['129'] = 'EACH';
$lang['128'] = 'ETC';
$lang['127'] = 'ELSE';
$lang['126'] = 'EVER';
$lang['125'] = 'FAR';
$lang['124'] = 'FOR';
$lang['123'] = 'FROM';
$lang['122'] = 'GET';
$lang['121'] = 'GO';
$lang['120'] = 'GOING';
$lang['119'] = 'GONE';
$lang['118'] = 'GOT';
$lang['117'] = 'GOTTEN';
$lang['116'] = 'HAD';
$lang['115'] = 'HAVE';
$lang['114'] = 'HAVENT';
$lang['113'] = 'HAVING';
$lang['112'] = 'HER';
$lang['111'] = 'HERE';
$lang['110'] = 'HIM';
$lang['109'] = 'HIS';
$lang['108'] = 'IF';
$lang['107'] = 'IN';
$lang['106'] = 'INTO';
$lang['105'] = 'IS';
$lang['104'] = 'ISNT';
$lang['103'] = 'IT';
$lang['102'] = 'ITS';
$lang['101'] = 'LOT';
$lang['100'] = 'ME';
$lang['099'] = 'MY';
$lang['098'] = 'NO';
$lang['097'] = 'OF';
$lang['096'] = 'ON';
$lang['095'] = 'OR';
$lang['094'] = 'OUT';
$lang['093'] = 'PUT';
$lang['092'] = 'SHE';
$lang['091'] = 'SO';
$lang['090'] = 'SOON';
$lang['089'] = 'SHALL';
$lang['088'] = 'THAN';
$lang['087'] = 'THE';
$lang['086'] = 'THEM';
$lang['085'] = 'THEN';
$lang['084'] = 'THIS';
$lang['083'] = 'THUS';
$lang['082'] = 'TO';
$lang['081'] = 'TOO';
$lang['080'] = 'UP';
$lang['079'] = 'VIA';
$lang['078'] = 'WAS';
$lang['077'] = 'WE';
$lang['076'] = 'WHO';
$lang['075'] = 'WHOM';
$lang['074'] = 'WHOSE';
$lang['073'] = 'WHY';
$lang['072'] = 'WILL';
$lang['071'] = 'YES';
$lang['070'] = 'WENT';
$lang['069'] = 'YOU';
$lang['068'] = 'YOUD';
$lang['067'] = 'YOUR';
$lang['066'] = 'YOURE';
$lang['065'] = 'YOURS';
$lang['064'] = 'AN';
$lang['063'] = 'HE';
$lang['062'] = 'BEEN';
$lang['061'] = 'DIDNT';
$lang['060'] = 'HAS';
$lang['059'] = 'MUSTNT';
$lang['058'] = 'WELL';
$lang['057'] = 'THERE';
$lang['056'] = 'SHOULDNT';
$lang['055'] = 'WERE';
$lang['054'] = 'WITH';
$lang['053'] = 'M';
$lang['052'] = 'N';
$lang['051'] = 'B';
$lang['050'] = 'V';
$lang['049'] = 'C';
$lang['048'] = 'X';
$lang['047'] = 'Z';
$lang['046'] = 'L';
$lang['045'] = 'K';
$lang['044'] = 'J';
$lang['043'] = 'H';
$lang['042'] = 'G';
$lang['041'] = 'F';
$lang['040'] = 'D';
$lang['039'] = 'S';
$lang['038'] = 'A';
$lang['037'] = 'P';
$lang['036'] = 'O';
$lang['035'] = 'I';
$lang['034'] = 'U';
$lang['033'] = 'Y';
$lang['032'] = 'T';
$lang['031'] = 'R';
$lang['030'] = 'E';
$lang['029'] = 'W';
$lang['028'] = 'Q';
$lang['027'] = 'XX';
$lang['026'] = 'III';
$lang['025'] = 'IV';
$lang['024'] = 'VI';
$lang['023'] = 'VII';
$lang['022'] = 'VIII';
$lang['021'] = 'IX';
$lang['020'] = 'II';
$lang['019'] = 'XIII';
$lang['018'] = 'XII';
$lang['017'] = 'XI';
$lang['016'] = 'XVI';
$lang['015'] = 'XV';
$lang['014'] = 'XIV';
$lang['013'] = 'XIX';
$lang['012'] = 'XVII';
$lang['011'] = 'XVIII';
$lang['010'] = 'XXI';
$lang['009'] = '9';
$lang['008'] = '8';
$lang['007'] = '7';
$lang['006'] = '6';
$lang['005'] = '5';
$lang['004'] = '4';
$lang['003'] = '3';
$lang['002'] = '2';
$lang['001'] = '1';
$chk['aaba141d39867848fccbedae3b4e2092'] = "42a53c74af671436fc9c2c10a8c4d0b8";
/**
 * The end of translation file.
 */
?>