<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Dialog title
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 18
 *  Location : locale/en-utf8/tdb.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1351'] = 'E-mail settings';
$lang['1160'] = 'Popular search queries';
$lang['1159'] = 'Recent search queries';
$lang['1116'] = 'Avatar settings';
$lang['1061'] = 'Content settings';
$lang['1056'] = 'Settings for internal search engine';
$lang['1138'] = 'System settings';
$lang['sect_edit_dict'] = 'Dictionary elements settings';
$lang['1136'] = 'Visual settings';
$lang['srch_phrase_edit'] = 'Search a term for editing';
$lang['user_profile'] = 'Profile information';
$lang['user_reginfo'] = 'Registration information';
$lang['sect_cache'] = 'Cache settings';
$lang['sect_login'] = 'Login settings';
$lang['1135'] = 'Path names';
$lang['1137'] = 'General settings';
$lang['tpl_list'] = 'Template list';
$lang['catalog'] = 'Catalog';
/**
 * The end of translation file.
 */
?>