<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Table header title
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 21
 *  Location : locale/en-utf8/tht.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1358'] = 'System files';
$lang['1357'] = 'Menu item';
$lang['1266'] = 'Backup';
$lang['1106'] = 'Contact information';
$lang['1037'] = 'Permissions';
$lang['1028'] = 'Database version';
$lang['r_term_updated'] = 'Recently updated terms';
$lang['recent'] = 'Recently added';
$lang['action'] = 'Action';
$lang['r_term_newest'] = 'Last added terms';
$lang['r_dict_updated'] = 'Recently updated dictionaries';
$lang['2_tip'] = 'Tips';
$lang['2_page_dict_browse'] = 'The list of dictionaries';
$lang['order'] = 'Order';
$lang['title_search'] = 'Search terms';
$lang['th_5'] = 'Last post';
$lang['th_4'] = 'Hits total';
$lang['th_3'] = 'Hits average';
$lang['th_1'] = 'Name';
$lang['r_dict_averagehits'] = 'Most popular dictionaries';
$lang['r_dict_newest'] = 'Last added dictionaries';
/**
 * The end of translation file.
 */
?>