<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Tool tip
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 29
 *  Location : locale/en-utf8/tol.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['tip032'] = 'A custom PHP-code which should be executed for the page. For example:
<ul class="noindent">
<li><tt>print_r( $arV );</tt> - display all page settings.</li>
<li><tt>print_r( $sys );</tt> - display all system settings.</li>
<li><tt>$oTpl->addVal( \'v:custom_var\', \'123\');</tt> - add text `123\'
if <tt>{%v:custom_var%}</tt> is presented in the page contents 
or in the HTML-templates.</li>
</ul>';
$lang['tip031'] = 'Page identifier, used with enabled <tt>mod_rewrite</tt>.';
$lang['tip030'] = 'Page contents. Possible variables are:
<ul class="noindent">
<li><tt>{%block:page_descr%}</tt> - page short description;</li>
<li><tt>{%subpages_cnt%}</tt> - the number of nested pages;</li>
<li><tt>{%subpages_ul%}</tt> - the list of nested pages, titles only.</li>
<li><tt>{%subpages_dl%}</tt> - the list of nested pages with short description;</li>
</ul>';
$lang['tip029'] = 'Page short description. Used in the list of nested pages.';
$lang['tip028'] = 'Page title';
$lang['tip027'] = 'Convert escape sequences into characters. \t will be converted into &amp;#009;.';
$lang['tip026'] = 'Keep whitespace characters, &amp;#009; will be saved.';
$lang['tip025'] = 'Enter a name to use as login. Non-latin characters are supported.';
$lang['tip024'] = 'You only need to confirm your password if you changed it above.';
$lang['tip023'] = 'You only need to supply a new password if you want to change current.';
$lang['tip022'] = 'You must confirm your current password if you wish to change it.';
$lang['tip021'] = 'Dictionary &#8594; Browse &#8594; Select dictionary from topic &#8594; Edit &#8594; check &quot;Published&quot; then click on &quot;Save&quot;.';
$lang['tip020'] = 'Dictionary &#8594; Browse &#8594; Select dictionary from topic &#8594; Add a term &#8594; Fill the form, then click on &quot;Save&quot;.';
$lang['tip019'] = 'Dictionary &#8594; Add &#8594; Fill the form, then click on &quot;Save&quot;.';
$lang['tip016'] = 'Create a new dictionary';
$lang['tip015'] = '%s - new last %d days.';
$lang['tip013'] = 'Additionally check terms with special characters like !, @, #, $ etc.';
$lang['tip012'] = 'Overwrite existent terms and definitions.';
$lang['tip011'] = 'Check to validate XML-code.';
$lang['tip010'] = 'Name the dictionary.';
$lang['tip009'] = 'Enter announce text for the catalog.';
$lang['tip008'] = 'Enter description for the dictionary title page.';
$lang['tip007'] = 'Enter keywords. Separate each keyword with comma (,). Used for META-tag on the dictionary pages.';
$lang['tip006'] = 'Select a topic from catalog.';
$lang['tip005'] = 'Select language for the dictionary interface. For multilingual dictionaries, select the default system language.';
$lang['tip004'] = 'Select directory name where HTML-templates are stored.';
$lang['tip001'] = 'Export values which were added or updated during specified timeframe.';
$lang['tip003'] = 'Name the dictionary database table, use [0-9a-z] only. Cannot be changed later.';
$lang['tip002'] = 'Separate terms with a new line.';
/**
 * The end of translation file.
 */
?>