services:
  php:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.glossword.rule=Host(`glossword.local`)"
      - "traefik.http.routers.glossword.entrypoints=web"
      - "traefik.http.services.glossword.loadbalancer.server.port=80"

  phpmyadmin:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.glossword-db.rule=Host(`db.glossword.local`)"
      - "traefik.http.routers.glossword-db.entrypoints=web"
      - "traefik.http.services.glossword-db.loadbalancer.server.port=80"
