<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Action names (to do)
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 58
 *  Location : locale/ru-utf8/actions.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1362'] = 'Мои установки';
$lang['1305'] = 'Очистить историю изменений';
$lang['1295'] = 'Откат';
$lang['1284'] = 'Просмотреть ключевые слова';
$lang['1283'] = 'Просмотреть термин';
$lang['1005'] = 'Объединить словари';
$lang['24_hours'] = '24 часа';
$lang['1105'] = 'Отправить e-mail';
$lang['1095'] = 'Предложить термин';
$lang['1093'] = 'Отписаться';
$lang['1087'] = 'Подписаться';
$lang['1072'] = 'Переместить';
$lang['1036'] = 'Отправить';
$lang['1035'] = 'Пред. просмотр';
$lang['1007'] = 'Получить HTML-код формы поиска';
$lang['1006'] = 'Очистить кэш поисковых фраз';
$lang['1023'] = 'Вы уверены в том, чтобы очистить кэш?';
$lang['1004'] = 'Использование кэш';
$lang['1003'] = 'Пересчитать количество терминов для каждого словаря';
$lang['1002'] = 'Проверить на незадействованные ключевые слова';
$lang['1001'] = 'Отправить сообщение в техническую поддержку Glossword';
$lang['3_maintenance'] = 'Обслуживание';
$lang['page_refresh'] = 'Обновить страницу';
$lang['2_continue'] = 'Продолжить';
$lang['3_property'] = 'Свойства';
$lang['3_change'] = 'Сменить';
$lang['3_logout'] = 'Выход';
$lang['3_send'] = 'Отправить';
$lang['3_add_term'] = 'Добавить термин';
$lang['3_next'] = 'Далее';
$lang['3_register'] = 'Регистрация';
$lang['3_import'] = 'Импорт';
$lang['3_clean'] = 'Очистить';
$lang['3_add_dict'] = 'Создать словарь';
$lang['3_browse'] = 'Список';
$lang['3_cancel'] = 'Отменить';
$lang['3_save'] = 'Сохранить';
$lang['1_prevd'] = 'Предыдущие %d';
$lang['1_nextd'] = 'Следующие %d';
$lang['1_prevpage'] = 'Пред.';
$lang['3_reset'] = 'Сброс';
$lang['3_down'] = 'Вниз';
$lang['3_up'] = 'Вверх';
$lang['3_more'] = 'Далее&#8230;';
$lang['3_export'] = 'Экспорт';
$lang['3_create'] = 'Создать';
$lang['3_edit'] = 'Правка';
$lang['3_remove_term'] = 'Удалить термин';
$lang['3_remove_defn'] = 'Удалить определение';
$lang['3_remove_trns'] = 'Удалить перевод';
$lang['3_remove_abbr'] = 'Удалить аббревиатуру';
$lang['3_remove'] = 'Удалить';
$lang['3_add_defn'] = 'Добавить определение';
$lang['3_add_trns'] = 'Добавить перевод';
$lang['3_add_abbr'] = 'Добавить аббревиатуру';
$lang['3_add'] = 'Добавить';
$lang['3_cfg'] = 'Конфигурация';
$lang['3_update'] = 'Обновить';
/**
 * The end of translation file.
 */
?>