<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Virtual keyboards
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/ru-utf8/addon_virtual-keyboards.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1307'] = 'Введите буквы, разделенные запятой (например: Ä,Á,Ă)';
$lang['2_page_virtual_keyboard_browse'] = 'Список виртуальных клавиатур';
$lang['1306'] = 'Буквы';
/**
 * The end of translation file.
 */
?>