<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Visual themes
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 7
 *  Location : locale/ru-utf8/addon_visual-themes.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1148'] = 'Создать новую цветовую схему';
$lang['1147'] = 'Объединить с цветовой схемой';
$lang['1146'] = 'Выбор цветовой схемы повлечет объединение импортируемых данных с уже существующей схемой, с перезаписью всех установок.';
$lang['1145'] = 'Встраиваемые блоки';
$lang['1143'] = 'Титульная страница';
$lang['1142'] = 'Переменные';
$lang['1141'] = 'Цвета';
/**
 * The end of translation file.
 */
?>