<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Export to SQL
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 8
 *  Location : locale/ru-utf8/export_sql.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1041'] = 'Использовать шестнадцатиричный формат';
$lang['sql_dict_stats'] = 'Включить информацию о посещаемости';
$lang['sql_dict_descr'] = 'Включить описание словаря';
$lang['sql_s_and_d'] = 'Структуру и данные';
$lang['sql_keywords'] = 'Включить слова для поисковой машины';
$lang['sql_droptable'] = 'Добавить &quot;DROP TABLE&quot;';
$lang['sql_data'] = 'Данные';
$lang['sql_structure'] = 'Структуру';
/**
 * The end of translation file.
 */
?>