<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : HTML Editor
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 19
 *  Location : locale/ru-utf8/html_editor.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['ed_tagopen'] = 'тэг открывается';
$lang['ed_tagclose'] = 'тег закрывается';
$lang['ed_dots'] = 'троеточие';
$lang['ed_degree'] = 'градусы';
$lang['ed_registered'] = 'знак Зарегистрировано';
$lang['ed_copyright'] = 'знак Авторское право';
$lang['ed_eurosign'] = 'знак Eвро';
$lang['ed_trademark'] = 'торговая марка';
$lang['ed_underline'] = 'подчеркнутый';
$lang['prompt_url'] = 'Введите URL (например http://glossword.info/)';
$lang['prompt_lnk'] = 'Укажите ссылку (слово для поиска в словаре)';
$lang['prompt_txt'] = 'Введите текст ссылки (текст, на котором будет стоять ссылка)';
$lang['ed_nbsp'] = 'неразрывный пробел';
$lang['ed_quot'] = 'кавычки';
$lang['ed_lapki'] = 'лапки';
$lang['ed_elochki'] = 'елочки';
$lang['ed_p'] = 'параграф';
$lang['ed_em'] = 'наклонный';
$lang['ed_bold'] = 'полужирный';
/**
 * The end of translation file.
 */
?>