<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Mail messages
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/ru-utf8/mail.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['1350'] = 'Автоматическое уведомление от сайта %s';
$lang['mail_newuser_subj'] = 'Добро пожаловать на сайт {SITENAME}';
$lang['mail_newpass_subj'] = 'Новый пароль';
$lang['mail_newuser'] = '<p>Здравствуйте, {USERNAME}</p>
<p>Пожалуйста, сохраните параметры вашей учётной записи:</p>
<p>{LOGIN}: <b>{U_LOGIN}</b> <br />{PASSWORD}: <b>{U_PASSWORD}</b></p>
<p>Вход в систему находится по адресу <br/>{LOGIN_URL}</p>
<p>Если вам что-то непонятно в работе сервиса, пишите на {CONTACT_EMAIL}.</p>';
$lang['mail_newpass'] = '<p>Здравствуйте, {USERNAME}.</p> <p>Вы просили выслать новый пароль к вашей учётной записи на сайте {SITENAME}.</p> <p>Чтобы использовать новый пароль, перейдите по ссылке: <br/> {U_ACTIVATE}</p>';
$lang['2_page_user_register'] = 'Регистрация нового пользователя';
/**
 * The end of translation file.
 */
?>