<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Current status (present tense)
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 9
 *  Location : locale/ru-utf8/status.php
 *  Created  : 17 Aug 2008, 01:59
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <team at glossword.biz>
 */
$lang['2_page_custom_az_browse'] = 'Просмотр профилей';
$lang['2_page_term_viewkeywords'] = 'Просмотр ключевых поисковых слов';
$lang['2_page_term_browse'] = 'Список терминов';
$lang['1107'] = 'Просмотр профиля';
$lang['2_page_32'] = 'Просмотр текущих подписок';
$lang['2_page_sys_maintenance'] = 'Обслуживание системы';
$lang['2_page_user_browse'] = 'Список пользователей';
$lang['2_page_17'] = 'Обновление термина';
$lang['2_page__srch'] = 'Поиск...';
/**
 * The end of translation file.
 */
?>