<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Common words to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://glossword.info/tkit/)
 *  � 2002-2004 Dmitry N. Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Common words
 *  Topic    : Stop words
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 191
 *  Location : locale/ru-utf8/stop_words.php
 *  Created  : 24 Aug 2003, 23:52
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry <dev at glossword dot info>
 */

$lang['195'] = 'КВТ';
$lang['194'] = 'ТЫС';
$lang['193'] = 'ММ';
$lang['192'] = 'КОГО';
$lang['191'] = 'СТР';
$lang['190'] = 'УЛ';
$lang['189'] = 'Я';
$lang['188'] = 'Ю';
$lang['187'] = 'Э';
$lang['186'] = 'Ы';
$lang['185'] = 'Щ';
$lang['184'] = 'Ш';
$lang['183'] = 'Ч';
$lang['182'] = 'Ц';
$lang['181'] = 'Х';
$lang['180'] = 'Ф';
$lang['179'] = 'У';
$lang['178'] = 'Т';
$lang['177'] = 'С';
$lang['176'] = 'Р';
$lang['175'] = 'П';
$lang['174'] = 'О';
$lang['173'] = 'Н';
$lang['172'] = 'М';
$lang['171'] = 'Л';
$lang['170'] = 'К';
$lang['169'] = 'Й';
$lang['168'] = 'И';
$lang['167'] = 'З';
$lang['166'] = 'Ж';
$lang['165'] = 'Е';
$lang['164'] = 'Д';
$lang['163'] = 'Г';
$lang['162'] = 'В';
$lang['161'] = 'Б';
$lang['160'] = 'А';
$lang['159'] = 'ПЕР';
$lang['158'] = 'ПРОСП';
$lang['157'] = 'ОС';
$lang['156'] = 'КОРП';
$lang['155'] = 'ДР';
$lang['154'] = 'КОГОЧТО';
$lang['153'] = 'КАК';
$lang['152'] = 'БЫ';
$lang['151'] = 'БЫТЬ';
$lang['150'] = 'КО';
$lang['149'] = 'ВО';
$lang['148'] = 'ВОТ';
$lang['147'] = 'ВСЕ';
$lang['146'] = 'ВЫ';
$lang['145'] = 'ГДЕ';
$lang['144'] = 'БЕЗ';
$lang['143'] = 'ДА';
$lang['142'] = 'ДЛЯ';
$lang['141'] = 'ДО';
$lang['140'] = 'ЕГО';
$lang['139'] = 'ЕЕ';
$lang['138'] = 'ЕЩЕ';
$lang['137'] = 'ЖЕ';
$lang['136'] = 'ЗА';
$lang['135'] = 'ЛИ';
$lang['134'] = 'ИЗ';
$lang['133'] = 'ИЛИ';
$lang['132'] = 'ИМ';
$lang['131'] = 'ИХ';
$lang['130'] = 'МЫ';
$lang['129'] = 'НА';
$lang['128'] = 'НЕ';
$lang['127'] = 'НЕЕ';
$lang['126'] = 'НЕТ';
$lang['125'] = 'НИ';
$lang['124'] = 'НО';
$lang['123'] = 'НУ';
$lang['122'] = 'ОБ';
$lang['121'] = 'ОН';
$lang['120'] = 'ОТ';
$lang['119'] = 'ПО';
$lang['118'] = 'ПОД';
$lang['117'] = 'ПРИ';
$lang['116'] = 'СО';
$lang['115'] = 'ТАК';
$lang['114'] = 'ТАМ';
$lang['113'] = 'ТЕ';
$lang['112'] = 'ТО';
$lang['111'] = 'ТЫ';
$lang['110'] = 'УЖЕ';
$lang['109'] = 'ЧЕМ';
$lang['108'] = 'ЧТО';
$lang['107'] = 'ЭТА';
$lang['106'] = 'ЭТИ';
$lang['105'] = 'ЭТО';
$lang['104'] = 'ТЫС';
$lang['103'] = 'КМ2';
$lang['102'] = 'МЛН';
$lang['101'] = 'КВТ';
$lang['100'] = 'МЛРД';
$lang['099'] = 'НАПР';
$lang['098'] = 'ЛИБО';
$lang['097'] = 'НАД';
$lang['096'] = 'ЛИШЬ';
$lang['095'] = 'ТОГО';
$lang['094'] = 'ИБО';
$lang['093'] = 'ТАКЖЕ';
$lang['092'] = 'ЧЕМУ';
$lang['091'] = 'ЧЕГО';
$lang['090'] = 'ЭТОЙ';
$lang['089'] = 'ЭТОМ';
$lang['088'] = 'ЭТОТ';
$lang['087'] = 'ЭТУ';
$lang['086'] = 'ЧТОБЫ';
$lang['085'] = 'ТУТ';
$lang['084'] = 'РАЗ';
$lang['083'] = 'ОНИ';
$lang['082'] = 'ОНА';
$lang['081'] = 'ЕМУ';
$lang['080'] = 'МЕНЯ';
$lang['079'] = 'МНЕ';
$lang['078'] = 'МОИ';
$lang['077'] = 'ТЕМ';
$lang['076'] = 'МОЕ';
$lang['075'] = 'НИХ';
$lang['074'] = 'БЫЛ';
$lang['073'] = 'САМ';
$lang['072'] = 'КТО';
$lang['071'] = 'ЕСТЬ';
$lang['070'] = 'ВЕДЬ';
$lang['069'] = 'НЕЙ';
$lang['068'] = 'НАС';
$lang['067'] = 'ТОТ';
$lang['066'] = 'НАМ';
$lang['065'] = 'НИМ';
$lang['064'] = 'ПРО';
$lang['063'] = 'ХОТЬ';
$lang['062'] = 'ВЕСЬ';
$lang['061'] = 'ВАС';
$lang['060'] = 'НЕМУ';
$lang['059'] = 'ВСЮ';
$lang['058'] = 'МОЙ';
$lang['057'] = 'ТОЙ';
$lang['056'] = 'МОЯ';
$lang['055'] = 'ТОЖЕ';
$lang['054'] = 'ТЕХ';
$lang['053'] = 'M';
$lang['052'] = 'N';
$lang['051'] = 'B';
$lang['050'] = 'V';
$lang['049'] = 'C';
$lang['048'] = 'X';
$lang['047'] = 'Z';
$lang['046'] = 'L';
$lang['045'] = 'K';
$lang['044'] = 'J';
$lang['043'] = 'H';
$lang['042'] = 'G';
$lang['041'] = 'F';
$lang['040'] = 'D';
$lang['039'] = 'S';
$lang['038'] = 'A';
$lang['037'] = 'P';
$lang['036'] = 'O';
$lang['035'] = 'I';
$lang['034'] = 'U';
$lang['033'] = 'Y';
$lang['032'] = 'T';
$lang['031'] = 'R';
$lang['030'] = 'E';
$lang['029'] = 'W';
$lang['028'] = 'Q';
$lang['027'] = 'XX';
$lang['026'] = 'III';
$lang['025'] = 'IV';
$lang['024'] = 'VI';
$lang['023'] = 'VII';
$lang['022'] = 'VIII';
$lang['021'] = 'IX';
$lang['020'] = 'II';
$lang['019'] = 'XIII';
$lang['018'] = 'XII';
$lang['016'] = 'XVI';
$lang['015'] = 'XV';
$lang['014'] = 'XIV';
$lang['013'] = 'XIX';
$lang['012'] = 'XVII';
$lang['011'] = 'XVIII';
$lang['010'] = 'XXI';
$lang['009'] = '9';
$lang['008'] = '8';
$lang['007'] = '7';
$lang['006'] = '6';
$lang['005'] = '5';
$lang['004'] = '4';
$lang['003'] = '3';
$lang['002'] = '2';
$lang['001'] = '1';
$chk['f9e4f9415713a92d3df869ebaada48b6'] = "e7dd16b89a6ebf815df25c7d2c3fb48a";
/**
 * The end of translation file.
 */
