<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Visual themes
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 7
 *  Location : locale/en-utf8/addon_visual-themes.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1148'] = 'Create a new visual theme';
$lang['1147'] = 'Merge into theme';
$lang['1146'] = 'Selecting a style will cause the imported style to be merged into an existing style, overwriting all settings.';
$lang['1145'] = 'Embedded blocks';
$lang['1143'] = 'Title page';
$lang['1142'] = 'Variables';
$lang['1141'] = 'Colors';
/**
 * The end of translation file.
 */
?>