<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Export to SQL
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 8
 *  Location : locale/en-utf8/export_sql.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1041'] = 'Use hexadecimal format';
$lang['sql_dict_stats'] = 'Include dictionary statistics';
$lang['sql_dict_descr'] = 'Include dictionary description';
$lang['sql_s_and_d'] = 'Structure and data';
$lang['sql_keywords'] = 'Include keywords for search engine';
$lang['sql_droptable'] = 'Add &quot;DROP TABLE&quot;';
$lang['sql_data'] = 'Data';
$lang['sql_structure'] = 'Structure';
/**
 * The end of translation file.
 */
?>