<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Installation
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 86
 *  Location : locale/en-utf8/l_install.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1253'] = 'You should accomplish all steps to complete update.';
$lang['1252'] = 'Due to major changes in the new version of program, this script will reset:
1) the list of previously added users
2) several dictionary settings
3) date of creation and modification for terms
4) the list of topics';
$lang['1251'] = 'This update is designed for version %s of the software.';
$lang['1250'] = 'Make sure you have a backup copy of all Glossword database tables.';
$lang['1249'] = 'Update complete';
$lang['1248'] = 'Updating table <tt>‘%s’</tt>';
$lang['1247'] = 'Updating dictionaries';
$lang['1246'] = 'Completing update';
$lang['1245'] = 'Updating database';
$lang['1244'] = 'Important notes';
$lang['1243'] = 'This update includes the following:';
$lang['1242'] = 'No connection to database.';
$lang['1241'] = 'Check username and password in file <tt>‘%s’</tt>.';
$lang['1240'] = 'The software is not installed.';
$lang['1239'] = '<a href="%s">Run installation script</a>.';
$lang['1238'] = 'Possible reasons:';
$lang['1237'] = 'Can\'t read settings from database.';
$lang['1236'] = 'The software uninstalled';
$lang['1235'] = 'You may remove the contents of folder <tt>‘%s’</tt>';
$lang['1234'] = 'Found';
$lang['1233'] = 'Not found';
$lang['1232'] = 'Unable to write file ‘%s’.';
$lang['1231'] = 'Locking setup wizard';
$lang['1230'] = 'Installation complete';
$lang['1229'] = 'Writing configuration file';
$lang['1228'] = 'Importing dictionaries';
$lang['1227'] = 'Importing visual themes';
$lang['1225'] = 'Importing topics';
$lang['1224'] = 'Creating database tables';
$lang['1223'] = 'Optional extension ‘mysqli’ does not exist.
You need to upgrade your PHP version to get a fully optimized database setup.';
$lang['1222'] = 'Optional extension ‘mysqli’ exists.';
$lang['1221'] = 'Could not connect to <tt>‘%s’</tt>
using username <tt>‘%s’</tt>.';
$lang['1220'] = 'Database <tt>‘%s’</tt> created.';
$lang['1219'] = 'Could not select database <tt>‘%s’</tt>.';
$lang['1218'] = 'Connection to database <tt>‘%s’</tt> established.';
$lang['1217'] = 'Unable to create new database. 
Possibly, you do not have such permissions.
Usually, a hosting company allows you to create database 
using hosting control panel.';
$lang['1216'] = 'Specify a database name.';
$lang['1215'] = 'Database already exists. Please type another database name.';
$lang['1211'] = 'Path to directory with Glossword files, usually <tt>‘/glossword’</tt>. 
No ending slashes. 
Leave empty when installing into root directory.';
$lang['1210'] = 'Script path';
$lang['1209'] = 'Database host (usually localhost)';
$lang['1208'] = 'Database name';
$lang['1207'] = 'Server host or domain name';
$lang['1206'] = 'Protocol';
$lang['1205'] = 'Prefix for database tables';
$lang['1204'] = 'Database password';
$lang['1203'] = 'Database username';
$lang['1202'] = 'Database configuration';
$lang['1201'] = 'Server configuration';
$lang['1200'] = 'Create new database (requires permission to create databases)';
$lang['1199'] = 'Use an existent database (requires permission to create and drop tables in the specified database)';
$lang['1198'] = '<p>If you do not know your database configuration, 
please check with company, which provides you hosting services.</p>

<p class="red">Important: this installer will delete any current 
database tables if you are using the same table prefix.</p>';
$lang['1196'] = 'Decline';
$lang['1195'] = 'Accept';
$lang['1194'] = 'Do you accept all the terms of the preceding License Agreement?';
$lang['1193'] = 'Use the scroll bar or press the Page Down key to navigate the agreement.';
$lang['1192'] = '<p>Please review the terms of the GNU General Public License below before installing %s.</p>';
$lang['1191'] = 'Checking for access permissions';
$lang['1190'] = 'Checking for PHP-version';
$lang['1189'] = 'Completing installation';
$lang['1188'] = 'Configuring settings';
$lang['1187'] = 'License Agreement';
$lang['1186'] = '<p>Installation:</p>';
$lang['1184'] = 'You cannot continue, reload this page (press F5) when you have corrected the errors above.';
$lang['1183'] = 'Continue to the next step.';
$lang['1182'] = 'Extensions not found.';
$lang['1181'] = 'Searching for PHP extensions';
$lang['1180'] = 'Optional extension ‘mbstring’ does not exist. 
You need to upgrade PHP version for faster contents indexing.';
$lang['1179'] = '‘mbstring’ extension found. This enables much faster indexing of contents.';
$lang['1178'] = 'Optional extension ‘iconv’ does not exist. 
You need to upgrade PHP version in order to have ability to convert charset encodings.';
$lang['1177'] = '‘iconv’ extension found. Ability to convert charset encodings found.';
$lang['1176'] = 'Mandatory extension ‘%s’ does not exist.';
$lang['1175'] = 'Mandatory extension ‘%s’ exists.';
$lang['1174'] = 'Access denied. Set write permissions to <tt>‘%s’</tt> (<strong>chmod 0666</strong> should be sufficient for files, <strong>chmod 0777</strong> for directory)';
$lang['1173'] = 'Access allowed. Enabled to write <tt>‘%s’</tt>.';
$lang['1172'] = 'Version of PHP is too old on this server. Version %s or better is required.';
$lang['1171'] = 'PHP version %s';
$lang['1170'] = 'Creating database';
$lang['1169'] = 'Checking system requirements';
$lang['1167'] = '<p>The installer is locked!</p>
<p>Before to run this script, you need to remove or rename the <tt>‘%s’</tt> file. It can be done with any FTP-client software (Filezilla, FlashFXP, and others).</p>';
$lang['1166'] = 'Uninstall';
$lang['1165'] = 'Upgrade from version %s to %s';
$lang['1164'] = 'New installation';
$lang['1163'] = 'Select type of installation';
$lang['1162'] = 'If you have problems with this script please visit <a href="%s">support page</a>.';
$lang['1161'] = 'Welcome to the %s setup wizard';
/**
 * The end of translation file.
 */
?>