<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom pages
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/ru-utf8/addon_custom-pages.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1157'] = 'Удалить эту страницу';
$lang['1156'] = 'Выщестояшая страница';
$lang['2_page_custom_pages_browse'] = 'Список индивидуальных страниц';
/**
 * The end of translation file.
 */
?>