<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Search Log
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 1
 *  Location : locale/ru-utf8/addon_log-search.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['log_search'] = 'Журнал поисковых запросов';
/**
 * The end of translation file.
 */
?>