<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Topics
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 5
 *  Location : locale/ru-utf8/addon_topics.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['2_page_topic_browse'] = 'Список тем';
$lang['3_undertopic'] = 'Вышестоящая тема';
$lang['3_add_subtopic'] = 'Добавить подтему';
$lang['3_remove_topic'] = 'Удалить тему';
$lang['3_add_topic'] = 'Создать тему';
/**
 * The end of translation file.
 */
?>