<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Abbreviation
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/ru-utf8/addon_abbr.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['id_dict_help'] = 'Словарь, в котором будет использоваться аббревиатура.';
$lang['id_abbr_help'] = 'ID аббревиатуры, используйте только [0-9]. После создания это поле сменить нельзя. Используется в <tt>&lt;(abbr|trns) lang=&quot;{Abbreviation ID}&quot;&gt;</tt>.';
$lang['id_abbr'] = 'ID аббревиатуры';
$lang['science'] = 'Наука';
$lang['languages'] = 'Названия языков';
$lang['linguistics'] = 'Лингвистика';
$lang['speech'] = 'Части речи';
$lang['custom'] = 'Индивидуальные';
$lang['id_group'] = 'Группа';
$lang['abbr_long'] = 'Полная форма';
$lang['abbr_short'] = 'Краткая форма';
/**
 * The end of translation file.
 */
?>