<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Virtual keyboards
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/ru-utf8/addon_virtual-keyboards.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1307'] = 'Введите буквы, разделенные запятой (например: Ä,Á,Ă)';
$lang['2_page_virtual_keyboard_browse'] = 'Список виртуальных клавиатур';
$lang['1306'] = 'Буквы';
/**
 * The end of translation file.
 */
?>