<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : General
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/ru-utf8/export.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['select_format'] = 'Выберите формат данных';
$lang['dictdump_split'] = 'Деление на строки';
$lang['timeframe'] = 'Период';
$lang['dictdump_fmt'] = 'Формат данных';
$lang['dictdump_files'] = 'Файлы';
$lang['dictdump_custom'] = 'Другое';
/**
 * The end of translation file.
 */
?>