<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Dialog title
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 18
 *  Location : locale/ru-utf8/tdb.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1351'] = 'Установки e-mail';
$lang['1160'] = 'Популярные поисковы запросы';
$lang['1159'] = 'Недавние поисковые запросы';
$lang['1116'] = 'Установки аватара';
$lang['1061'] = 'Установки содержимого';
$lang['1056'] = 'Установки внутренней поисковой машины';
$lang['1138'] = 'Системные настройки';
$lang['sect_edit_dict'] = 'Настройка элементов словаря';
$lang['1136'] = 'Визуальные настройки';
$lang['srch_phrase_edit'] = 'Искать термин для редактирования';
$lang['user_profile'] = 'Профиль';
$lang['user_reginfo'] = 'Регистрационная информация';
$lang['sect_cache'] = 'Настройка кэш';
$lang['sect_login'] = 'Настройки логина';
$lang['1135'] = 'Имена каталогов';
$lang['1137'] = 'Общие настройки';
$lang['tpl_list'] = 'Список шаблонов';
$lang['catalog'] = 'Каталог';
/**
 * The end of translation file.
 */
?>