<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Table header title
 *  Language : Russian
 *  Charset  : UTF-8
 *  Phrases  : 21
 *  Location : locale/ru-utf8/tht.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 */
$lang['1358'] = 'Системные файлы';
$lang['1357'] = 'Пункт меню';
$lang['1266'] = 'Резервирование данных';
$lang['1106'] = 'Контактная информация';
$lang['1037'] = 'Права доступа';
$lang['1028'] = 'Версия базы данных';
$lang['r_term_updated'] = 'Обновленные термины';
$lang['recent'] = 'Недавно добавленное';
$lang['action'] = 'Действие';
$lang['r_term_newest'] = 'Новые термины';
$lang['r_dict_updated'] = 'Обновленные словари';
$lang['2_tip'] = 'Справка';
$lang['2_page_dict_browse'] = 'Список словарей';
$lang['order'] = 'Порядок';
$lang['title_search'] = 'Поиск терминов';
$lang['th_5'] = 'Дата публикации';
$lang['th_4'] = 'Хитов всего';
$lang['th_3'] = 'Хитов в&#160;среднем';
$lang['th_1'] = 'Название';
$lang['r_dict_averagehits'] = 'Популярные словари';
$lang['r_dict_newest'] = 'Недавно добавленные словари';
/**
 * The end of translation file.
 */
?>