<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Action names (to do)
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 58
 *  Location : locale/es-utf8/actions.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1362'] = 'Mi configuración';
$lang['1305'] = 'Limpiar el historial de cambios';
$lang['1295'] = 'Revertir';
$lang['1284'] = 'Ver palabras clave';
$lang['1283'] = 'Ver término';
$lang['1005'] = 'Combinar diccionarios';
$lang['24_hours'] = '24 Horas';
$lang['1105'] = 'Enviar un email';
$lang['1095'] = 'Sugerir un término';
$lang['1093'] = 'Darse de baja';
$lang['1087'] = 'Subscribirse';
$lang['1072'] = 'Mover a';
$lang['1036'] = 'Enviar';
$lang['1035'] = 'Vista previa';
$lang['1007'] = 'Código HTML para el formulario de búsqueda';
$lang['1006'] = 'Limpiar la caché de búsqueda';
$lang['1023'] = '¿Está seguro de limpiar la caché?';
$lang['1004'] = 'Uso de la caché';
$lang['1003'] = 'Recontar el número de términos de cada diccionario';
$lang['1002'] = 'Comprobar palabras clave no usadas';
$lang['1001'] = 'Enviar un mensaje al equipo de soporte de Glossword';
$lang['3_maintenance'] = 'Mantenimiento';
$lang['page_refresh'] = 'Actualizar';
$lang['2_continue'] = 'Continuar';
$lang['3_property'] = 'Propiedades';
$lang['3_change'] = 'Cambiar';
$lang['3_logout'] = 'Cerrar sesión';
$lang['3_send'] = 'Enviar';
$lang['3_add_term'] = 'Añadir término';
$lang['3_next'] = 'Siguiente';
$lang['3_register'] = 'Nueva cuenta';
$lang['3_import'] = 'Importar';
$lang['3_clean'] = 'Limpiar';
$lang['3_add_dict'] = 'Nuevo diccionario';
$lang['3_browse'] = 'Consultar';
$lang['3_cancel'] = 'Cancelar';
$lang['3_save'] = 'Grabar';
$lang['1_prevd'] = 'Anterior %d';
$lang['1_nextd'] = 'Siguiente %d';
$lang['1_prevpage'] = 'Anterior';
$lang['3_reset'] = 'Reiniciar';
$lang['3_down'] = 'Abajo';
$lang['3_up'] = 'Arriba';
$lang['3_more'] = 'Más&#8230;';
$lang['3_export'] = 'Exportar';
$lang['3_create'] = 'Crear';
$lang['3_edit'] = 'Editar';
$lang['3_remove_term'] = 'Eliminar este término';
$lang['3_remove_defn'] = 'Eliminar esta definición';
$lang['3_remove_trns'] = 'Eliminar esta traducción';
$lang['3_remove_abbr'] = 'Eliminar esta abreviatura';
$lang['3_remove'] = 'Eliminar';
$lang['3_add_defn'] = 'Añadir una definición';
$lang['3_add_trns'] = 'Añadir una traducción';
$lang['3_add_abbr'] = 'Añadir una abreviatura';
$lang['3_add'] = 'Añadir';
$lang['3_cfg'] = 'Configuración';
$lang['3_update'] = 'Actualizar';
/**
 * The end of translation file.
 */
?>