<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Virtual keyboards
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/es-utf8/addon_virtual-keyboards.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1307'] = 'Introduzca letras separadas por comas (ejemplo: Ä,Á,Ă)';
$lang['2_page_virtual_keyboard_browse'] = 'Lista de teclados virtuales';
$lang['1306'] = 'Letras';
/**
 * The end of translation file.
 */
?>