<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom pages
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/es-utf8/addon_custom-pages.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1157'] = 'Eliminar esta página';
$lang['1156'] = 'Página padre';
$lang['2_page_custom_pages_browse'] = 'Lista de páginas personalizadas';
/**
 * The end of translation file.
 */
?>