<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Topics
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 5
 *  Location : locale/es-utf8/addon_topics.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['2_page_topic_browse'] = 'Lista de categorías';
$lang['3_undertopic'] = 'Categoría padre';
$lang['3_add_subtopic'] = 'Añadir subcategoría';
$lang['3_remove_topic'] = 'Eliminar esta categoría';
$lang['3_add_topic'] = 'Nueva categoría';
/**
 * The end of translation file.
 */
?>