<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Administrative interface
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 23
 *  Location : locale/es-utf8/admin.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1086'] = 'No hay suscripciones activas.';
$lang['3_subscription'] = 'Suscripciones';
$lang['1024'] = 'Adjunte la información del sistema para obtener la respuesta más adecuada.';
$lang['1022'] = 'Caché de fichero, bytes';
$lang['1021'] = 'Número de objetos en caché';
$lang['1020'] = 'Caché de búsquedas, bytes';
$lang['1019'] = 'La base de datos está optimizada';
$lang['1018'] = 'Las palabras clave no usadas han sido eliminadas';
$lang['1017'] = 'No hay palabras clave que eliminar';
$lang['1016'] = '¿Está seguro de querer optimizar la base de datos?';
$lang['1015'] = 'Tamaño medio después de optimizar, bytes';
$lang['1014'] = 'Tamaño medio ahorrado, bytes';
$lang['1013'] = 'Tamaño actual de la base de datos, bytes';
$lang['1012'] = 'Número de palabras clave indexadas después de optimizar';
$lang['1011'] = 'Número de palabras clave no usadas';
$lang['1010'] = 'Número de palabras clave';
$lang['1009'] = '<p>Esta tarea comprobará si hay palabras clave no usadas en la base de datos. Si se encontrara alguna, puede usted eliminarla para ahorrar algunos kilobytes en el disco y para mejorar un poco la prestación del mecanismo de búsqueda.</p>

<p>La tarea rquiere un esfuerzo importante de la base de datos. El tiempo total de ejecución depende del número total de palabras clave existentes, así que puede durar varios minutos.</p>

<p>Por favor, tenga en cuenta que las palabras clave no usadas son de gran ayuda para añadir términos en el futuro porque el proceso de importar nuevos términos funciona más rápido con las palabras clave existentes. Mientras tanto, sólo ocupan bytes en la base de datos.</p>';
$lang['1008'] = 'Comprobar palabras clave no usadas';
$lang['pass_confirm'] = 'Confirmar contraseña';
$lang['pass_new'] = 'Nueva contraseña';
$lang['pass_current'] = 'Contraseña actual';
$lang['2_page__'] = 'Inicio Panel de Control';
$lang['securenote'] = 'Sólo para uso interno';
/**
 * The end of translation file.
 */
?>