<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Error message
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 39
 *  Location : locale/es-utf8/err.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1370'] = 'Algunos campos son incorrectos.';
$lang['1348'] = 'No hay ítems seleccionados';
$lang['1347'] = 'Tiempo máximo de inactividad permitido, minutos: %s';
$lang['1346'] = 'Minutos transcurridos: %s';
$lang['1345'] = 'Se requiere autorización. La sesión no existe.';
$lang['1344'] = 'Usted ha cerrado sesión.';
$lang['1343'] = 'Se requiere autorización. La sesión no existe.';
$lang['1342'] = 'Sesión caducada en caso de inactividad.';
$lang['1297'] = 'No se encontraron registros.';
$lang['1255'] = 'No hay datos';
$lang['1254'] = 'Demasiados registros. El número máximo es: %s. Ha introducido: %s.';
$lang['1090'] = 'Dirección de email incorrecta. Pruebe de nuevo.';
$lang['1079'] = 'Errores';
$lang['reason_26'] = 'El término no existe';
$lang['reason_25'] = 'El término ya existe';
$lang['reason_24'] = 'Su cuenta ha sido activada. El nombre de usario y la contraseña han sido enviados al email que indicó en la página de registro.';
$lang['reason_23'] = 'Clave de activación incorrecta';
$lang['reason_22'] = 'Se ha generado una nueva contraseña. La clave de activación ha sido enviada al email que indicó en la página de registro.';
$lang['reason_21'] = 'Lo sentimos pero su cuenta está inactiva actualmente. Por favor, póngase en contacto con el administrador del sitio para más información';
$lang['reason_20'] = 'Ha introducido un nombre de usuario incorrecto o una contraseña no válida.';
$lang['reason_19'] = 'La contraseña introducida es demasiado larga';
$lang['reason_18'] = 'Esa dirección de correo no puede ser usada porque ya existe';
$lang['reason_17'] = 'No se pudo enviar un correo a %s';
$lang['reason_16'] = 'La cuenta actual está desactivada o en espera de activación';
$lang['reason_15'] = 'Seleccionó un nombre de usuario que ya existe. Pruebe con otro';
$lang['reason_14'] = 'Las nuevas contraseñas no coinciden. Pruebe otra vez';
$lang['reason_13'] = 'Permiso denegado';
$lang['reason_12'] = 'No existe tal categoría';
$lang['reason_11'] = 'No se pudo eliminar';
$lang['reason_10'] = 'Fichero `%s` no encontrado';
$lang['reason_9'] = 'Incorrecto';
$lang['reason_8'] = 'La función %s no está instalada';
$lang['reason_6'] = 'Imposible cargar la extensión PHP `iconv` o `recode`';
$lang['reason_5'] = 'No hay resultados';
$lang['reason_4'] = 'No se encontraron diccionarios';
$lang['reason_3'] = 'Diccionarios encontrados en esta categoría';
$lang['reason_2'] = 'Hay más categorías dentro de esta categoría.';
$lang['reason_1'] = 'Última categoría. Al menos una de las categorías debe existir';
$lang['reason_7'] = 'No se encontraron diccionarios';
/**
 * The end of translation file.
 */
?>