<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Export to SQL
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 8
 *  Location : locale/es-utf8/export_sql.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1041'] = 'Usar formato hexadecimal';
$lang['sql_dict_stats'] = 'Incluir estadísticas del diccionario';
$lang['sql_dict_descr'] = 'Incluir descripción del diccionario';
$lang['sql_s_and_d'] = 'Estructura y datos';
$lang['sql_keywords'] = 'Incluir palabras clave para buscadores';
$lang['sql_droptable'] = 'Añadir &quot;DROP TABLE&quot;';
$lang['sql_data'] = 'Datos';
$lang['sql_structure'] = 'Estructura';
/**
 * The end of translation file.
 */
?>