<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : General
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/es-utf8/export.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['select_format'] = 'Seleccionar un formato de datos';
$lang['dictdump_split'] = 'Separación por líneas';
$lang['timeframe'] = 'Periodo de tiempo';
$lang['dictdump_fmt'] = 'Formato de salida';
$lang['dictdump_files'] = 'Ficheros';
$lang['dictdump_custom'] = 'Otro número';
/**
 * The end of translation file.
 */
?>