<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : HTML Editor
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 19
 *  Location : locale/es-utf8/html_editor.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['ed_tagopen'] = 'abrir etiqueta';
$lang['ed_tagclose'] = 'cerrar etiqueta';
$lang['ed_dots'] = 'puntos suspensivos';
$lang['ed_degree'] = 'grados';
$lang['ed_registered'] = 'marca registrada';
$lang['ed_copyright'] = 'copyright';
$lang['ed_eurosign'] = 'símbolo del euro';
$lang['ed_trademark'] = 'marca comercial';
$lang['ed_underline'] = 'subrayado';
$lang['prompt_url'] = 'Introducir URL (Ejemplo: http://glossword.info/)';
$lang['prompt_lnk'] = 'Introducir enlace (término para la búsqueda)';
$lang['prompt_txt'] = 'Introducir texto (Este texto será enlazado)';
$lang['ed_nbsp'] = 'espacio inseparable';
$lang['ed_quot'] = 'comillas';
$lang['ed_lapki'] = 'comillas';
$lang['ed_elochki'] = 'comillas';
$lang['ed_p'] = 'párrafo';
$lang['ed_em'] = 'cursiva';
$lang['ed_bold'] = 'negrita';
/**
 * The end of translation file.
 */
?>