<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Mail messages
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/es-utf8/mail.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1350'] = 'Notificación automática del sitio %s';
$lang['mail_newuser_subj'] = 'Bienvenido a {SITENAME}';
$lang['mail_newpass_subj'] = 'Activación de nueva contraseña';
$lang['mail_newuser'] = '<p>Estimado usuario: {USERNAME}.</p>
<p>Por favor, guarde este email para referencias futuras. Información de su cuenta:</p>
<p>{LOGIN}: <b>{U_LOGIN}</b><br />{PASSWORD}: <b>{U_PASSWORD}</b></p>
<p>Utilice la siguiente dirección para acceder al panel de administración: <br />{LOGIN_URL}</p>
<p>Si tiene alguna pregunta, contacte con {CONTACT_EMAIL}.</p>';
$lang['mail_newpass'] = '<p>Estimado usuario: {USERNAME}</p>
<p>Ha solicitado una nueva contraseña para su cuenta en {SITENAME}.</p>
<p>Para usar la nueva contraseña debe hacer clic en el siguiente enlace: <br/>
{U_ACTIVATE}</p>';
$lang['2_page_user_register'] = 'Registro de nuevo usuario';
/**
 * The end of translation file.
 */
?>