<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Option text
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 201
 *  Location : locale/es-utf8/options.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1401'] = 'Mostrar зor defecto'; //to translate
$lang['1374'] = 'Guardar en el hisorial de cambios';
$lang['1369'] = 'Tiempo de ejecución de la tarea';
$lang['1364'] = 'ID del diccionario';
$lang['1361'] = 'Permitir acceso simultáneo';
$lang['1360'] = 'Publicar los términos importados';
$lang['1359'] = 'Combinar términos idénticos';
$lang['1356'] = 'UTC Tiempo universal coordinado';
$lang['1355'] = 'Autorizado a editar su propio perfil';
$lang['1354'] = 'Recibir eventos del sistema';
$lang['1352'] = 'Prefijo para el asunto';
$lang['1330'] = 'Añadir componente';
$lang['1329'] = 'Añadir ítem de menú';
$lang['1328'] = 'Icono';
$lang['1327'] = 'Crear un nuevo';
$lang['1326'] = 'Oculto';
$lang['1325'] = 'Menú secundario';
$lang['1324'] = 'Menú primario';
$lang['1323'] = 'Emplazamiento';
$lang['1322'] = 'Cadena de traducción';
$lang['1321'] = 'Nombre del fichero';
$lang['1320'] = 'Publicado';
$lang['1319'] = 'Gestor de menús';
$lang['1318'] = 'Autorizado a editar las páginas de otros usuarios';
$lang['1317'] = 'Autorizado a editar sus propias páginas';
$lang['1316'] = 'Autorizado a cambiar contraseña';
$lang['1315'] = 'Autorizado a cambiar acceso (login)';
$lang['1314'] = 'Autorizado a cambiar dirección de email';
$lang['1313'] = 'Autorizado a ejecutar tareas de mantenimiento';
$lang['1312'] = 'Autorizado a editar las categorías de otros usuarios';
$lang['1311'] = 'No escriba signos diacríticos si no quiere incluirlos en la ordenación';
$lang['1310'] = 'Mayúsculas';
$lang['1309'] = 'Ordenar';
$lang['1308'] = 'Los términos incompletos están marcados con el símbolo ‘%s’';
$lang['1304'] = 'Habilitar SEF (URL amigables para los buscadores)';
$lang['1303'] = 'Modo de creación de enlaces';
$lang['1302'] = 'De texto';
$lang['1301'] = 'Alfanumérico';
$lang['1300'] = 'Sólo numérico';
$lang['1299'] = 'Guardar como fichero';
$lang['1298'] = 'Listar términos eliminados';
$lang['1296'] = 'Número de días en el historial de cambios';
$lang['1294'] = 'Historial de cambios';
$lang['1288'] = 'Mostrar';
$lang['1287'] = 'Como lista';
$lang['1286'] = 'Como tabla';
$lang['1280'] = 'Insensible a mayúsculas y minúsculas (A = a).';
$lang['1279'] = 'Recargar imagen';
$lang['1278'] = 'E-mail de un amigo';
$lang['1275'] = 'Enviar la página';
$lang['1274'] = 'Ordenar';
$lang['1273'] = 'Por nombre';
$lang['1272'] = 'Por fecha';
$lang['1271'] = 'Añadir a búsqueda';
$lang['1270'] = 'Como en la configuración del sistema';
$lang['1268'] = 'Listar términos incompletos';
$lang['1267'] = 'El término está completo';
$lang['1265'] = 'Autorizado a editar la configuración del programa';
$lang['1264'] = 'Autorizado a exportar términos';
$lang['1263'] = 'Autorizado a importar términos';
$lang['1262'] = 'Autorizado a editar su configuración de usuario';
$lang['1261'] = 'Autorizado a crear y editar sus propios términos';
$lang['1260'] = 'Autorizado a editar la configuración de diccionario de otros usuarios';
$lang['1259'] = 'Autorizado a editar los términos de otros usuarios';
$lang['1258'] = 'Autorizado a crear y editar sus propios diccionarios';
$lang['1257'] = 'Autorizado a crear y editar sus propias categorías';
$lang['1256'] = 'Activar enlaces para los términos de este campo';
$lang['1197'] = 'Usar las ventajas de Content-Type para navegadores compatibles con XHTML 1.1';
$lang['1158'] = 'Combinar los valores nuevos con los existentes';
$lang['1154'] = 'Mostrar las descripciones de las categorías en el catálogo';
$lang['1153'] = 'Incluir la fecha de creación y modificación';
$lang['1152'] = 'Los valores importados reemplazarán por completo los existentes';
$lang['srch_topic'] = 'Buscar en categoría';
$lang['srch_dict'] = 'Buscar en diccionario';
$lang['1150'] = 'términos/segundo';
$lang['1149'] = 'Velocidad media';
$lang['1140'] = 'Autor';
$lang['1139'] = 'Comprobar si un término ya existe';
$lang['1128'] = 'Número de días de las búsquedas en caché';
$lang['1127'] = 'Limpiar los diccionarios seleccionados después de combinar';
$lang['1126'] = 'Para seleccionar varios ítems use la tecla CTRL y el botón izquierdo del ratón.';
$lang['1125'] = 'Seleccione uno o más diccionarios para combinar.';
$lang['1124'] = 'Los diccionarios seleccionados serán combinados con';
$lang['1123'] = 'Leer la primera línea';
$lang['1122'] = 'Definiciones terminadas con';
$lang['1120'] = 'Campos delimitados por';
$lang['1119'] = 'Campos terminados con';
$lang['1118'] = 'Activar automáticamente los hiperenlaces';
$lang['1117'] = 'La imagen será reducida si su tamaño en píxeles es demasiado grande.';
$lang['1132'] = 'Tamaño máximo, kilobytes';
$lang['1130'] = 'Anchura máxima, píxeles';
$lang['1131'] = 'Altura máxima, píxeles';
$lang['is_abbr_long'] = 'Mostrar la forma larga de las abreviaturas';
$lang['1129'] = 'Número de días en el log de búsquedas';
$lang['period'] = 'Periodo';
$lang['is_use_avatar'] = 'Usar avatar';
$lang['1111'] = 'Su avatar actual';
$lang['1110'] = 'Se permiten los siguientes tipos de fichero';
$lang['srch_7'] = 'Listar términos no aprobados';
$lang['is_show_date_modified'] = 'Mostratr fecha de modificación';
$lang['is_show_authors'] = 'Mostrar la lista de editores';
$lang['1103'] = 'La hora, incluyendo el ajuste actual es';
$lang['1101'] = 'Habilitar el registro de búsquedas';
$lang['1100'] = 'Habilitar el registro de correos electrónicos';
$lang['1099'] = 'Habilitar el registro de páginas de referencia';
$lang['1098'] = 'Carácter usado como separador en el camino de navegación';
$lang['1097'] = 'Carácter usado como separador en &lt;title&gt;';
$lang['1096'] = 'Número de términos por página con resultados de búsqueda';
$lang['1084'] = 'Seleccione un diccionario';
$lang['1080'] = 'Asunto';
$lang['1077'] = 'Suscriptores';
$lang['1074'] = 'Añadir subpágina';
$lang['1073'] = 'Identificador uniforme de recursos (URI)';
$lang['1068'] = 'Ruta de los ficheros exportados';
$lang['1066'] = 'Mostrar la descripción corta del diccionario en el catálogo.';
$lang['1065'] = 'Mostrar iconos en el catálogo.';
$lang['1064'] = 'Mostrar el número de términos del diccionario en el catálogo.';
$lang['1063'] = 'Número de diccionarios en el Top 10';
$lang['1062'] = 'Número de diccionarios actualizados recientemente';
$lang['1060'] = 'Fichero del icono';
$lang['1059'] = 'Código de programa';
$lang['1058'] = 'Contenido';
$lang['1055'] = 'Sensible a letras [a-z y letras de alfabetos nacionales]';
$lang['1054'] = 'Sensible a caracteres alfanuméricos [a-z0-9]';
$lang['1053'] = 'Caracteres ideográficos';
$lang['1052'] = 'Formas de media anchura y de anchura completa';
$lang['1051'] = 'Signos diacríticos';
$lang['1050'] = 'Basic Latin';
$lang['1049'] = 'Sensible a signos diacríticos [a-ž]';
$lang['1048'] = 'Sensible a números [0-9]';
$lang['1047'] = 'Filtrar stopwords';
$lang['1046'] = 'Filtrar caracteres especiales';
$lang['1045'] = 'Mostrar la definición del término en un globo';
$lang['1044'] = 'Compatibilidad de versiones';
$lang['1040'] = 'Convertir secuencias de escape';
$lang['1039'] = 'Mantener caracteres de espacio en blanco';
$lang['1038'] = 'La búsqueda está desactivada';
$lang['1034'] = 'Errores de documentación';
$lang['1033'] = 'Errores de traducción de la interfaz';
$lang['1032'] = 'Temas de personalización';
$lang['1031'] = 'Sugerencias y peticiones';
$lang['1030'] = 'Temas de configuración';
$lang['1029'] = 'Temas generales';
$lang['1027'] = 'Sistema operativo';
$lang['1026'] = 'Versión de PHP';
$lang['1025'] = 'Versión del producto';
$lang['is_dict_as_index'] = 'Asignar este diccionario como página principal';
$lang['is_show_full'] = 'Mostrar el texto completo de las definiciones';
$lang['after_post_3'] = 'Abrir los últimos resultados de búsqueda';
$lang['after_post_is_save_term'] = 'Guardar la configuración del formato HTML';
$lang['after_post_1'] = 'Actualizar las estadísticas del diccionario';
$lang['after_post'] = 'Al&#160;ejecutar…';
$lang['xml_is_term_id'] = 'ID del término';
$lang['alphabetic_order'] = 'Orden alfabético';
$lang['fields_to_edit'] = 'Campos para editar';
$lang['min_srch_length'] = 'Longitud mínima de la cadena de búsqueda';
$lang['user_notice'] = 'Enviar notificación de registro';
$lang['allow_user'] = 'Acceso permitido';
$lang['allow_htmleditor'] = 'Utilizar Editor de HTML';
$lang['allow_leecher'] = 'Activar anti-leecher';
$lang['user_dictionaries'] = 'Diccionarios asignados';
$lang['date_logged'] = 'Fecha del último acceso';
$lang['date_register'] = 'Registrado el';
$lang['allow_showcontact'] = 'Mostrar información de contacto';
$lang['lang_source'] = 'Idioma fuente';
$lang['is_specialchars'] = 'Incluir caracteres especiales cuando se comprueben términos existentes';
$lang['admin_url'] = 'Ruta de la página de administración';
$lang['login_url'] = 'Ruta de la página de acceso (login)';
$lang['admin_host'] = 'Servidor de administración';
$lang['login_host'] = 'Servidor de acceso';
$lang['admin_proto'] = 'Protocolo de administración';
$lang['login_proto'] = 'Protocolo de acceso (login)';
$lang['path_cache'] = 'Ruta de las consultas guardadas en caché';
$lang['path_log'] = 'Ruta de los ficheros de registro (log)';
$lang['site_desc'] = 'Descripción del sitio';
$lang['site_name'] = 'Nombre del sitio';
$lang['default_lang'] = 'Idioma por defecto';
$lang['cache_lifetime'] = 'La caché caduca en minutos (0 - no caduca)';
$lang['cache_zlib'] = 'Utilizar compresión GZip para almacenar/leer ficheros de caché';
$lang['cache_is'] = 'Activar motor de caché';
$lang['1133'] = 'El máximo número de caracteres por cada definición en la lista de términos';
$lang['time_upd'] = 'Número de días que un diccionario está marcado como actualizado';
$lang['time_new'] = 'Número de días que un diccionario está marcado como nuevo';
$lang['page_limit'] = 'Número de términos por página';
$lang['sys'] = 'Sistema';
$lang['enter_xml'] = 'Introducir código XML válido';
$lang['date_modif'] = 'Última modificación';
$lang['date_created'] = 'Creado el';
$lang['dict_name'] = 'Título';
$lang['announce'] = 'Descripción corta';
$lang['keywords'] = 'Palabras clave';
$lang['visual_theme'] = 'Tema visual';
$lang['srch_selectdict'] = 'Seleccionar diccionario';
$lang['validate'] = 'Validar';
$lang['overwrite'] = 'Sobreescribir valores existentes con los nuevos valores';
$lang['till_time'] = 'hasta';
$lang['from_time'] = 'desde';
$lang['dictdump_list'] = 'Desde la lista';
$lang['allow_letters'] = 'Mostrar la barra alfabética (A-Z)';
$lang['sysname'] = 'Nombre de la tabla en la base de datos';
$lang['options'] = 'Opciones';
$lang['ed_xref'] = 'Poner un enlace a un término';
/**
 * The end of translation file.
 */
?>