<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Common words to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://glossword.info/tkit/)
 *  © 2002-2004 Dmitry N. Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Common words
 *  Topic    : Stop words
 *  Language : English
 *  Charset  : UTF-8
 *  Phrases  : 146
 *  Location : locale/es-utf8/stop_words.php
 *  Created  : 25 Aug 2003, 00:25
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry <dev at glossword dot info>
 */
$lang['053'] = 'M';
$lang['052'] = 'N';
$lang['051'] = 'B';
$lang['050'] = 'V';
$lang['049'] = 'C';
$lang['048'] = 'X';
$lang['047'] = 'Z';
$lang['046'] = 'L';
$lang['045'] = 'K';
$lang['044'] = 'J';
$lang['043'] = 'H';
$lang['042'] = 'G';
$lang['041'] = 'F';
$lang['040'] = 'D';
$lang['039'] = 'S';
$lang['038'] = 'A';
$lang['037'] = 'P';
$lang['036'] = 'O';
$lang['035'] = 'I';
$lang['034'] = 'U';
$lang['033'] = 'Y';
$lang['032'] = 'T';
$lang['031'] = 'R';
$lang['030'] = 'E';
$lang['029'] = 'W';
$lang['028'] = 'Q';
$lang['027'] = 'XX';
$lang['026'] = 'III';
$lang['025'] = 'IV';
$lang['024'] = 'VI';
$lang['023'] = 'VII';
$lang['022'] = 'VIII';
$lang['021'] = 'IX';
$lang['020'] = 'II';
$lang['019'] = 'XIII';
$lang['018'] = 'XII';
$lang['017'] = 'XI';
$lang['016'] = 'XVI';
$lang['015'] = 'XV';
$lang['014'] = 'XIV';
$lang['013'] = 'XIX';
$lang['012'] = 'XVII';
$lang['011'] = 'XVIII';
$lang['010'] = 'XXI';
$lang['009'] = '9';
$lang['008'] = '8';
$lang['007'] = '7';
$lang['006'] = '6';
$lang['005'] = '5';
$lang['004'] = '4';
$lang['003'] = '3';
$lang['002'] = '2';
$lang['001'] = '1';
/**
 * The end of translation file.
 */
?>