<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Dialog title
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 18
 *  Location : locale/es-utf8/tdb.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1351'] = 'Configuración del email';
$lang['1160'] = 'Búsquedas populares';
$lang['1159'] = 'Búsquedas recientes';
$lang['1116'] = 'Configuración de los avatares';
$lang['1061'] = 'Configuración del contenido';
$lang['1056'] = 'Configuración del motor de búsqueda interno';
$lang['1138'] = 'Configuración del sistema';
$lang['sect_edit_dict'] = 'Configuración de elementos del diccionario';
$lang['1136'] = 'Configuración visual';
$lang['srch_phrase_edit'] = 'Buscar un término para editarlo';
$lang['user_profile'] = 'Información del perfil';
$lang['user_reginfo'] = 'Información del registro';
$lang['sect_cache'] = 'Configuración de la caché';
$lang['sect_login'] = 'Configuración del acceso (login)';
$lang['1135'] = 'Nombres de rutas';
$lang['1137'] = 'Configuración general';
$lang['tpl_list'] = 'Lista de plantillas';
$lang['catalog'] = 'Catálogo';
/**
 * The end of translation file.
 */
?>