<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Table header title
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 21
 *  Location : locale/es-utf8/tht.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1358'] = 'Ficheros del sistema';
$lang['1357'] = 'Ítem de menú';
$lang['1266'] = 'Copia de seguridad (backup)';
$lang['1106'] = 'Información de contacto';
$lang['1037'] = 'Permisos';
$lang['1028'] = 'Versión de la base de datos';
$lang['r_term_updated'] = 'Términos actualizados recientemente';
$lang['recent'] = 'Añadidos recientemente';
$lang['action'] = 'Acción';
$lang['r_term_newest'] = 'Últimos términos añadidos';
$lang['r_dict_updated'] = 'Diccionarios actualizados recientemente';
$lang['2_tip'] = 'Instrucciones';
$lang['2_page_dict_browse'] = 'Lista de los diccionarios';
$lang['order'] = 'Orden';
$lang['title_search'] = 'Buscar término';
$lang['th_5'] = 'Último envío';
$lang['th_4'] = 'Total de consultas';
$lang['th_3'] = 'Promedio de consultas';
$lang['th_1'] = 'Nombre';
$lang['r_dict_averagehits'] = 'Diccionarios más populares';
$lang['r_dict_newest'] = 'Últimos diccionarios añadidos';
/**
 * The end of translation file.
 */
?>