<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2008 Dmitry Shilnikov <team at glossword dot biz>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Tool tip
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 29
 *  Location : locale/es-utf8/tol.php
 *  Created  : 16 Aug 2008, 17:53
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['tip032'] = 'Un código PHP personalizado que debe ser ejecutado en la página. Por ejemplo:
<ul class="noindent">
<li><tt>print_r( $arV );</tt> - mostrar todos los ajustes de página.</li>
<li><tt>print_r( $sys );</tt> - mostrar todos los ajustes de sistema.</li>
<li><tt>$oTpl->addVal( \'v:custom_var\', \'123\');</tt> - añadir el texto ‘123’
si <tt>{%v:custom_var%}</tt> aparece en el contenido de la página 
o en las plantillas HTML.</li></ul>';
$lang['tip031'] = 'Identificador de página, usado con el <tt>mod_rewrite</tt> habilitado.';
$lang['tip030'] = 'Contenido de página. Algunas variables posibles son:
<ul class="noindent">
<li><tt>{%block:page_descr%}</tt> - descripción corta de la página.</li>
<li><tt>{%subpages_cnt%}</tt> - número de páginas anidadas.</li>
<li><tt>{%subpages_ul%}</tt> - lista de páginas anidadas, sólo títulos.</li>
<li><tt>{%subpages_dl%}</tt> - lista de páginas anidadas con descripción corta.</li>
</ul>';
$lang['tip029'] = 'Descripción corta de la página. Usada en la lista de páginas anidadas.';
$lang['tip028'] = 'Título de la página';
$lang['tip027'] = 'Convertir secuencias de escape en caracteres. \t se convertirá en &amp;#009;.';
$lang['tip026'] = 'Conservar los carateres de espacio en blanco, &amp;#009; se conservará.';
$lang['tip025'] = 'Introduzca un nombre de usuario. Se pueden usar caracteres no latinos.';
$lang['tip024'] = 'Sólo tiene que confirmar su contraseña si la cambió arriba.';
$lang['tip023'] = 'Sólo tiene que introducir una contraseña nueva si quiere cambiar la actual.';
$lang['tip022'] = 'Debe confirmar su contraseña actual si quiere cambiarla.';
$lang['tip021'] = 'Diccionario &#8594; Consultar &#8594; Seleccionar diccionario de categoría &#8594; Editar &#8594; Marcar &quot;Publicado&quot; y hacer clic en &quot;Grabar&quot;.';
$lang['tip020'] = 'Diccionario &#8594; Consultar &#8594; Seleccionar diccionario de categoría &#8594; Añadir un término &#8594; Rellenar el formulario y hacer clic en &quot;Grabar&quot;.';
$lang['tip019'] = 'Diccionario &#8594; Añadir &#8594; Rellenar el formulario y hacer clic en &quot;Grabar&quot;.';
$lang['tip016'] = 'Crear un nuevo diccionario';
$lang['tip015'] = '%s - nuevos últimos %d días.';
$lang['tip013'] = 'También comprobar términos con caracteres especiales como !, @, #, $ etc.';
$lang['tip012'] = 'Sobreescribir los términos y definiciones existentes.';
$lang['tip011'] = 'Marcar para validar código XML.';
$lang['tip010'] = 'Nombre del diccionario.';
$lang['tip009'] = 'Introducir texto anunciativo para el catálogo.';
$lang['tip008'] = 'Introducir descripción para la portada del diccionario.';
$lang['tip007'] = 'Introducir palabras clave. Separar cada palabra clave con una coma (,). Usadas para las metaetiquetas en las páginas del diccionario.';
$lang['tip006'] = 'Seleccionar una categoría del catálogo.';
$lang['tip005'] = 'Seleccionar idioma para la interfaz del diccionario. Para diccionarios multilingües, seleccionar el idioma por defecto del sistema.';
$lang['tip004'] = 'Seleccionar el directorio donde se almacenan las plantillas HTML.';
$lang['tip001'] = 'Exportar valores que se añadieron o actualizaron durante un periodo de tiempo especificado.';
$lang['tip003'] = 'Nombre para la tabla de base de datos. Sólo [0-9 a-z]. No se puede cambiar después.';
$lang['tip002'] = 'Separar términos con una nueva línea.';
/**
 * The end of translation file.
 */
?>