<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Visual themes
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 7
 *  Location : locale/es-utf8/addon_visual-themes.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1148'] = 'Crear un nuevo tema visual';
$lang['1147'] = 'Combinar con tema';
$lang['1146'] = 'Seleccionar un estilo hará que el estilo importado se combine con un estilo existente, sobrescribiendo todos los ajustes.';
$lang['1145'] = 'Bloques incrustados';
$lang['1143'] = 'Portada';
$lang['1142'] = 'Variables';
$lang['1141'] = 'Colores';
/**
 * The end of translation file.
 */
?>