<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom pages
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 8
 *  Location : locale/es-utf8/addon_custom_pages.php
 *  Created  : 26 Nov 2007, 07:30
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['2_page_custom_pages_import'] = 'Importar páginas personalizadas';
$lang['2_page_custom_pages_export'] = 'Exportar páginas personalizadas';
$lang['1157'] = 'Eliminar esta página';
$lang['1156'] = 'Página padre';
$lang['2_page_custom_pages_add'] = 'Crear página personalizada';
$lang['2_page_custom_pages_remove'] = 'Eliminar página personalizada';
$lang['2_page_custom_pages_edit'] = 'Editar configuración de página';
$lang['2_page_custom_pages_browse'] = 'Lista de páginas personalizadas';
/**
 * The end of translation file.
 */
?>