<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Search Log
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 5
 *  Location : locale/es-utf8/addon_log_search.php
 *  Created  : 26 Nov 2007, 07:30
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['2_page_log_search_clean'] = 'Limpiando el registro (log) de búsqueda';
$lang['2_page_log_search_rp02'] = 'Consultando las búsquedas';
$lang['2_page_log_search_browse'] = 'Consultando las búsquedas';
$lang['2_page_log_search_rp01'] = 'Consultando las búsquedas';
$lang['log_search'] = 'Log de búsquedas';
/**
 * The end of translation file.
 */
?>