<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Topics
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 9
 *  Location : locale/es-utf8/addon_topic.php
 *  Created  : 26 Nov 2007, 07:30
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1155'] = 'Publicar categoría';
$lang['2_page_topic_export'] = 'Exportando la lista de categorías';
$lang['2_page_topic_import'] = 'Importando la lista de categorías';
$lang['2_page_topic_remove'] = 'Eliminando la categoría';
$lang['2_page_topic_browse'] = 'Lista de categorías';
$lang['3_undertopic'] = 'Categoría padre';
$lang['3_add_subtopic'] = 'Añadir subcategoría';
$lang['3_remove_topic'] = 'Eliminar esta categoría';
$lang['3_add_topic'] = 'Nueva categoría';
/**
 * The end of translation file.
 */
?>