<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Abbreviation
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/es-utf8/addon_abbr.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['id_dict_help'] = 'Diccionario en el que se usará la abreviatura.';
$lang['id_abbr_help'] = 'ID de abreviatura, usar sólo [0-9]. No se puede cambiar después. Usado en <tt>&lt;(abbr|trns) lang=&quot;{Abbreviation ID}&quot;&gt;</tt>.';
$lang['id_abbr'] = 'ID de abreviatura';
$lang['science'] = 'Ciencias';
$lang['languages'] = 'Nombres de idiomas';
$lang['linguistics'] = 'Linguística';
$lang['speech'] = 'Partes de la oración';
$lang['custom'] = 'Personalizadas';
$lang['id_group'] = 'Grupo';
$lang['abbr_long'] = 'Forma larga';
$lang['abbr_short'] = 'Forma corta';
/**
 * The end of translation file.
 */
?>