<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom alphabetic order
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 10
 *  Location : locale/es-utf8/addon_custom_az.php
 *  Created  : 26 Nov 2007, 07:30
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1293'] = 'Ordenación por defecto';
$lang['1292'] = 'Letra';
$lang['1291'] = 'Activar el perfil';
$lang['1290'] = 'Perfil';
$lang['2_page_custom_az_update'] = 'Actualizando el perfil';
$lang['2_page_custom_az_browse'] = 'Consultando perfiles';
$lang['2_page_custom_az_edit'] = 'Editando el perfil';
$lang['2_page_custom_az_add'] = 'Añadiendo un perfil nuevo';
$lang['2_page_custom_az_remove'] = 'Eliminando el perfil';
$lang['1289'] = 'Nombre del perfil';
/**
 * The end of translation file.
 */
?>