<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Installation
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 86
 *  Location : locale/es-utf8/l_install.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['1253'] = 'Debe llevar a cabo todos los pasos para completar la actualización.';
$lang['1252'] = 'Debido a importantes cambios en la nueva versión del programa, este script reiniciará:
1) la lista de usuaros añadidos anteriormente
2) varios ajustes de los diccionarios
3) la fecha de creación y modificación de los términos
4) la lista de categorías';
$lang['1251'] = 'Esta actualización está diseñada para la versión %s del software.';
$lang['1250'] = 'Cerciórese de tener una copia de seguridad (backup) de todas las tablas de la base de datos de Glossword.';
$lang['1249'] = 'Actualización completada';
$lang['1248'] = 'Actualizando tabla <tt>‘%s’</tt>';
$lang['1247'] = 'Actualizando diccionarios';
$lang['1246'] = 'Completando actualización';
$lang['1245'] = 'Actualizando base de datos';
$lang['1244'] = 'Notas importantes';
$lang['1243'] = 'Esta actualización incluye lo siguiente:';
$lang['1242'] = 'No hay conexión con la base de datos.';
$lang['1241'] = 'Compruebe nombre de usuario y contraseña en el fichero <tt>‘%s’</tt>.';
$lang['1240'] = 'El software no está instalado.';
$lang['1239'] = '<a href="%s">Ponga en marcha el script de instalación</a>.';
$lang['1238'] = 'Posibles razones:';
$lang['1237'] = 'No se pueden leer los ajustes de la base de datos.';
$lang['1236'] = 'El software ha sido desinstalado';
$lang['1235'] = 'Puede eliminar el contenido de la carpeta <tt>‘%s’</tt>';
$lang['1234'] = 'Encontrado';
$lang['1233'] = 'No encontrado';
$lang['1232'] = 'No se puede ‘%s’.';
$lang['1231'] = 'Clausurando el asistente de instalación';
$lang['1230'] = 'Instalación completada';
$lang['1229'] = 'Escribiendo el archivo de configuración';
$lang['1228'] = 'Importando diccionarios';
$lang['1227'] = 'Importando temas visuales';
$lang['1225'] = 'Importando categorías';
$lang['1224'] = 'Creando tablas de la base de datos';
$lang['1223'] = 'La extensión opcional ‘mysqli’ no existe. Necesita actualizar su versión de PHP para obtener mayor rendimiento de la base de datos.';
$lang['1222'] = 'La extensión opcional ‘mysqli’ existe.';
$lang['1221'] = 'No se pudo conectar con <tt>‘%s’</tt> utilizando el nombre de usuario <tt>‘%s’</tt>.';
$lang['1220'] = 'Base de datos <tt>‘%s’</tt> creada.';
$lang['1219'] = 'No se pudo selecionar la base de datos <tt>‘%s’</tt>.';
$lang['1218'] = 'Conexión con la base de datos <tt>‘%s’</tt> establecida.';
$lang['1217'] = 'No se pudo crear una nueva base de datos. 
Posiblemente usted no tenga los permisos necesarios.
Habitualmente, las compañías de alojamiento le permiten crear bases de datos 
usando un panel de control del alojamiento.';
$lang['1216'] = 'Especifique un nombre de base de datos.';
$lang['1215'] = 'La base de datos ya existe. Por favor escriba otro nombre de base de datos.';
$lang['1211'] = 'Ruta del directorio que contiene los ficheros de Glossword, habitualmente <tt>‘/glossword’</tt>. 
Sin barra al final. 
Dejar vacío cuando se instala en el directorio raíz.';
$lang['1210'] = 'Ruta del script';
$lang['1209'] = 'Host de la base de datos (habitualmente localhost)';
$lang['1208'] = 'Nombre de base de datos';
$lang['1207'] = 'Host del servidor o nombre de dominio';
$lang['1206'] = 'Protocolo';
$lang['1205'] = 'Prefijo para las tablas de la base de datos';
$lang['1204'] = 'Contraseña de la base de datos';
$lang['1203'] = 'Nombre de usuario de la base de datos';
$lang['1202'] = 'Configuración de la base de datos';
$lang['1201'] = 'Configuración del servidor';
$lang['1200'] = 'Crear nueva base de datos (requiere permiso para crear bases de datos)';
$lang['1199'] = 'Usar una base de datos existente (requiere permiso para crear and eliminar tablas en la base de datos especificada)';
$lang['1198'] = '<p>Si no conoce la configuración de su base de datos, 
por favor, consulte con la empresa que le proporciona el servicio de alojamiento.</p>

<p class="red">Importante: este instalador borrará cualquier tabla actual  
de la base de datos si usa usted el mismo prefijo de tabla.</p>';
$lang['1196'] = 'Rechazar';
$lang['1195'] = 'Aceptar';
$lang['1194'] = '¿Acepta Ud. todos los términos del Acuerdo de Licencia precedente?';
$lang['1193'] = 'Use la barra de desplazamiento o pulse la tecla Av Pág (PgDn) para desplazarse por el acuerdo.';
$lang['1192'] = '<p>Por favor, revise los términos de la Licencia General Pública GNU que encontrará más abajo, antes de instalar %s.</p>';
$lang['1191'] = 'Comprobando permisos de acceso';
$lang['1190'] = 'Comprobando versión de PHP';
$lang['1189'] = 'Completando instalación';
$lang['1188'] = 'Configurando ajustes';
$lang['1187'] = 'Acuerdo de Licencia';
$lang['1186'] = '<p>Instalación:</p>';
$lang['1184'] = 'No puede continuar. Recargue esta página (pulsando F5) cuando haya corregido los errores que aparecen más arriba.';
$lang['1183'] = 'Puede continuar.';
$lang['1182'] = 'Extensiones no encontradas.';
$lang['1181'] = 'Buscando extensiones de PHP';
$lang['1180'] = 'La extensión opcional ‘mbstring’ no existe. Necesita actualizar la versión de PHP para que los contenidos se indexen más rápidamente.';
$lang['1179'] = 'La extensión ‘mbstring’ existe. La indexación de contenidos funciona mucho más rápidamente.';
$lang['1178'] = 'La extensión opcional ‘iconv’ no existe. Necesita actualizar la versión de PHP para poder convertir las codificaciones de caracteres.';
$lang['1177'] = 'La extensión ‘iconv’ existe. Se pueden convertir las codificaciones de caracteres.';
$lang['1176'] = 'La extensión obligatoria ‘%s’ no existe.';
$lang['1175'] = 'La extensión obligatoria ‘%s’ existe.';
$lang['1174'] = 'Acceso denegado. Establezca los permisos de escritura en <tt>‘%s’</tt> (<strong>chmod 0666</strong> debería bastar para ficheros y <strong>chmod 0777</strong> para directorios)';
$lang['1173'] = 'Acceso permitido. Habilitado para escribir <tt>‘%s’</tt>.';
$lang['1172'] = 'La versión de PHP de este servidor es demasiado antigua. Se requiere la versión %s o posterior.';
$lang['1171'] = 'Versión de PHP %s';
$lang['1170'] = 'Creando la base de datos';
$lang['1169'] = 'Comprobando requisitos de sistema';
$lang['1167'] = '<p>El instalador está clausurado</p> <p>Antes de usar el script, debe eliminar o renombrar el archivo <tt>‘%s’</tt>. Esto se puede hacer con cualquier software cliente de FTP (Filezilla, FlashFXP, u otros).</p>';
$lang['1166'] = 'Desinstalar';
$lang['1165'] = 'Actualizar de la versión %s a la %s';
$lang['1164'] = 'Nueva instalación';
$lang['1163'] = 'Seleccione tipo de instalación';
$lang['1162'] = 'Si tiene problemas con este script, por favor visite la <a href="%s">página de apoyo</a>.';
$lang['1161'] = 'Bienvenido/a al asistente de instalación de %s';
/**
 * The end of translation file.
 */
?>