<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Current status (present tense)
 *  Language : Spanish
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/es-utf8/status.php
 *  Created  : 09 Apr 2008, 01:56
 *  ------------------------------------------------------
 *  Translation created by:
 *      - José Marcos <elmoch at telefonica.net>
 */
$lang['2_page_custom_az_browse'] = 'Consultando perfiles';
$lang['2_page_term_rollback'] = 'Reversión';
$lang['2_page_term_viewhistory'] = 'Viendo el historial de cambios';
$lang['2_page_term_viewkeywords'] = 'Viendo palabras clave de búsqueda';
$lang['2_page_term_browse'] = 'Lista de términos';
$lang['1107'] = 'Ver perfil';
$lang['2_page_32'] = 'Consultando suscripciones actuales';
$lang['2_page_sys_maintenance'] = 'Mantenimiento del sistema';
$lang['2_page_user_browse'] = 'Lista de usuarios';
$lang['2_page_17'] = 'Actualizando un término';
$lang['2_page__srch'] = 'Buscando en';
/**
 * The end of translation file.
 */
?>